// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    [AirbyteResourceType("airbyte:index/destinationVertica:DestinationVertica")]
    public partial class DestinationVertica : global::Pulumi.CustomResource
    {
        [Output("configuration")]
        public Output<Outputs.DestinationVerticaConfiguration> Configuration { get; private set; } = null!;

        [Output("destinationId")]
        public Output<string> DestinationId { get; private set; } = null!;

        [Output("destinationType")]
        public Output<string> DestinationType { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("workspaceId")]
        public Output<string> WorkspaceId { get; private set; } = null!;


        /// <summary>
        /// Create a DestinationVertica resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DestinationVertica(string name, DestinationVerticaArgs args, CustomResourceOptions? options = null)
            : base("airbyte:index/destinationVertica:DestinationVertica", name, args ?? new DestinationVerticaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DestinationVertica(string name, Input<string> id, DestinationVerticaState? state = null, CustomResourceOptions? options = null)
            : base("airbyte:index/destinationVertica:DestinationVertica", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DestinationVertica resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DestinationVertica Get(string name, Input<string> id, DestinationVerticaState? state = null, CustomResourceOptions? options = null)
        {
            return new DestinationVertica(name, id, state, options);
        }
    }

    public sealed class DestinationVerticaArgs : global::Pulumi.ResourceArgs
    {
        [Input("configuration", required: true)]
        public Input<Inputs.DestinationVerticaConfigurationArgs> Configuration { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("workspaceId", required: true)]
        public Input<string> WorkspaceId { get; set; } = null!;

        public DestinationVerticaArgs()
        {
        }
        public static new DestinationVerticaArgs Empty => new DestinationVerticaArgs();
    }

    public sealed class DestinationVerticaState : global::Pulumi.ResourceArgs
    {
        [Input("configuration")]
        public Input<Inputs.DestinationVerticaConfigurationGetArgs>? Configuration { get; set; }

        [Input("destinationId")]
        public Input<string>? DestinationId { get; set; }

        [Input("destinationType")]
        public Input<string>? DestinationType { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("workspaceId")]
        public Input<string>? WorkspaceId { get; set; }

        public DestinationVerticaState()
        {
        }
        public static new DestinationVerticaState Empty => new DestinationVerticaState();
    }
}
