// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceTvmazeSchedule
    {
        public static Task<GetSourceTvmazeScheduleResult> InvokeAsync(GetSourceTvmazeScheduleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceTvmazeScheduleResult>("airbyte:index/getSourceTvmazeSchedule:getSourceTvmazeSchedule", args ?? new GetSourceTvmazeScheduleArgs(), options.WithDefaults());

        public static Output<GetSourceTvmazeScheduleResult> Invoke(GetSourceTvmazeScheduleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceTvmazeScheduleResult>("airbyte:index/getSourceTvmazeSchedule:getSourceTvmazeSchedule", args ?? new GetSourceTvmazeScheduleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceTvmazeScheduleArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceTvmazeScheduleArgs()
        {
        }
        public static new GetSourceTvmazeScheduleArgs Empty => new GetSourceTvmazeScheduleArgs();
    }

    public sealed class GetSourceTvmazeScheduleInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceTvmazeScheduleInvokeArgs()
        {
        }
        public static new GetSourceTvmazeScheduleInvokeArgs Empty => new GetSourceTvmazeScheduleInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceTvmazeScheduleResult
    {
        public readonly Outputs.GetSourceTvmazeScheduleConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceTvmazeScheduleResult(
            Outputs.GetSourceTvmazeScheduleConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
