// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceRecharge
    {
        public static Task<GetSourceRechargeResult> InvokeAsync(GetSourceRechargeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceRechargeResult>("airbyte:index/getSourceRecharge:getSourceRecharge", args ?? new GetSourceRechargeArgs(), options.WithDefaults());

        public static Output<GetSourceRechargeResult> Invoke(GetSourceRechargeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceRechargeResult>("airbyte:index/getSourceRecharge:getSourceRecharge", args ?? new GetSourceRechargeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceRechargeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceRechargeArgs()
        {
        }
        public static new GetSourceRechargeArgs Empty => new GetSourceRechargeArgs();
    }

    public sealed class GetSourceRechargeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceRechargeInvokeArgs()
        {
        }
        public static new GetSourceRechargeInvokeArgs Empty => new GetSourceRechargeInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceRechargeResult
    {
        public readonly Outputs.GetSourceRechargeConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceRechargeResult(
            Outputs.GetSourceRechargeConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
