// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceFauna
    {
        public static Task<GetSourceFaunaResult> InvokeAsync(GetSourceFaunaArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceFaunaResult>("airbyte:index/getSourceFauna:getSourceFauna", args ?? new GetSourceFaunaArgs(), options.WithDefaults());

        public static Output<GetSourceFaunaResult> Invoke(GetSourceFaunaInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceFaunaResult>("airbyte:index/getSourceFauna:getSourceFauna", args ?? new GetSourceFaunaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceFaunaArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceFaunaArgs()
        {
        }
        public static new GetSourceFaunaArgs Empty => new GetSourceFaunaArgs();
    }

    public sealed class GetSourceFaunaInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceFaunaInvokeArgs()
        {
        }
        public static new GetSourceFaunaInvokeArgs Empty => new GetSourceFaunaInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceFaunaResult
    {
        public readonly Outputs.GetSourceFaunaConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceFaunaResult(
            Outputs.GetSourceFaunaConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
