// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceSapFieldglass
    {
        public static Task<GetSourceSapFieldglassResult> InvokeAsync(GetSourceSapFieldglassArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceSapFieldglassResult>("airbyte:index/getSourceSapFieldglass:getSourceSapFieldglass", args ?? new GetSourceSapFieldglassArgs(), options.WithDefaults());

        public static Output<GetSourceSapFieldglassResult> Invoke(GetSourceSapFieldglassInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceSapFieldglassResult>("airbyte:index/getSourceSapFieldglass:getSourceSapFieldglass", args ?? new GetSourceSapFieldglassInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceSapFieldglassArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceSapFieldglassArgs()
        {
        }
        public static new GetSourceSapFieldglassArgs Empty => new GetSourceSapFieldglassArgs();
    }

    public sealed class GetSourceSapFieldglassInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceSapFieldglassInvokeArgs()
        {
        }
        public static new GetSourceSapFieldglassInvokeArgs Empty => new GetSourceSapFieldglassInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceSapFieldglassResult
    {
        public readonly Outputs.GetSourceSapFieldglassConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceSapFieldglassResult(
            Outputs.GetSourceSapFieldglassConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
