// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceBigcommerce
    {
        public static Task<GetSourceBigcommerceResult> InvokeAsync(GetSourceBigcommerceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceBigcommerceResult>("airbyte:index/getSourceBigcommerce:getSourceBigcommerce", args ?? new GetSourceBigcommerceArgs(), options.WithDefaults());

        public static Output<GetSourceBigcommerceResult> Invoke(GetSourceBigcommerceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceBigcommerceResult>("airbyte:index/getSourceBigcommerce:getSourceBigcommerce", args ?? new GetSourceBigcommerceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceBigcommerceArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceBigcommerceArgs()
        {
        }
        public static new GetSourceBigcommerceArgs Empty => new GetSourceBigcommerceArgs();
    }

    public sealed class GetSourceBigcommerceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceBigcommerceInvokeArgs()
        {
        }
        public static new GetSourceBigcommerceInvokeArgs Empty => new GetSourceBigcommerceInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceBigcommerceResult
    {
        public readonly Outputs.GetSourceBigcommerceConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceBigcommerceResult(
            Outputs.GetSourceBigcommerceConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
