// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceMailgun
    {
        public static Task<GetSourceMailgunResult> InvokeAsync(GetSourceMailgunArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceMailgunResult>("airbyte:index/getSourceMailgun:getSourceMailgun", args ?? new GetSourceMailgunArgs(), options.WithDefaults());

        public static Output<GetSourceMailgunResult> Invoke(GetSourceMailgunInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceMailgunResult>("airbyte:index/getSourceMailgun:getSourceMailgun", args ?? new GetSourceMailgunInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceMailgunArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceMailgunArgs()
        {
        }
        public static new GetSourceMailgunArgs Empty => new GetSourceMailgunArgs();
    }

    public sealed class GetSourceMailgunInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceMailgunInvokeArgs()
        {
        }
        public static new GetSourceMailgunInvokeArgs Empty => new GetSourceMailgunInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceMailgunResult
    {
        public readonly Outputs.GetSourceMailgunConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceMailgunResult(
            Outputs.GetSourceMailgunConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
