// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceSpaceXApi
    {
        public static Task<GetSourceSpaceXApiResult> InvokeAsync(GetSourceSpaceXApiArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceSpaceXApiResult>("airbyte:index/getSourceSpaceXApi:getSourceSpaceXApi", args ?? new GetSourceSpaceXApiArgs(), options.WithDefaults());

        public static Output<GetSourceSpaceXApiResult> Invoke(GetSourceSpaceXApiInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceSpaceXApiResult>("airbyte:index/getSourceSpaceXApi:getSourceSpaceXApi", args ?? new GetSourceSpaceXApiInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceSpaceXApiArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceSpaceXApiArgs()
        {
        }
        public static new GetSourceSpaceXApiArgs Empty => new GetSourceSpaceXApiArgs();
    }

    public sealed class GetSourceSpaceXApiInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceSpaceXApiInvokeArgs()
        {
        }
        public static new GetSourceSpaceXApiInvokeArgs Empty => new GetSourceSpaceXApiInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceSpaceXApiResult
    {
        public readonly Outputs.GetSourceSpaceXApiConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceSpaceXApiResult(
            Outputs.GetSourceSpaceXApiConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
