// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceGoogleAds
    {
        public static Task<GetSourceGoogleAdsResult> InvokeAsync(GetSourceGoogleAdsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceGoogleAdsResult>("airbyte:index/getSourceGoogleAds:getSourceGoogleAds", args ?? new GetSourceGoogleAdsArgs(), options.WithDefaults());

        public static Output<GetSourceGoogleAdsResult> Invoke(GetSourceGoogleAdsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceGoogleAdsResult>("airbyte:index/getSourceGoogleAds:getSourceGoogleAds", args ?? new GetSourceGoogleAdsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceGoogleAdsArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public string? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceGoogleAdsArgs()
        {
        }
        public static new GetSourceGoogleAdsArgs Empty => new GetSourceGoogleAdsArgs();
    }

    public sealed class GetSourceGoogleAdsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceGoogleAdsInvokeArgs()
        {
        }
        public static new GetSourceGoogleAdsInvokeArgs Empty => new GetSourceGoogleAdsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceGoogleAdsResult
    {
        public readonly Outputs.GetSourceGoogleAdsConfiguration Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? SecretId;
        public readonly string SourceId;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceGoogleAdsResult(
            Outputs.GetSourceGoogleAdsConfiguration configuration,

            string id,

            string name,

            string? secretId,

            string sourceId,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SecretId = secretId;
            SourceId = sourceId;
            WorkspaceId = workspaceId;
        }
    }
}
