// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetBearerAuth(ctx *pulumi.Context) string {
	return config.Get(ctx, "airbyte:bearerAuth")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "airbyte:password")
}

// Server URL (defaults to https://api.airbyte.com/v1)
func GetServerUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "airbyte:serverUrl")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "airbyte:username")
}
