// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationMSsqlConfigurationTunnelMethod
    {
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodNoTunnel? DestinationMssqlSshTunnelMethodNoTunnel;
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodPasswordAuthentication? DestinationMssqlSshTunnelMethodPasswordAuthentication;
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodSshKeyAuthentication? DestinationMssqlSshTunnelMethodSshKeyAuthentication;
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodNoTunnel? DestinationMssqlUpdateSshTunnelMethodNoTunnel;
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodPasswordAuthentication? DestinationMssqlUpdateSshTunnelMethodPasswordAuthentication;
        public readonly Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodSshKeyAuthentication? DestinationMssqlUpdateSshTunnelMethodSshKeyAuthentication;

        [OutputConstructor]
        private DestinationMSsqlConfigurationTunnelMethod(
            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodNoTunnel? destinationMssqlSshTunnelMethodNoTunnel,

            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodPasswordAuthentication? destinationMssqlSshTunnelMethodPasswordAuthentication,

            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlSshTunnelMethodSshKeyAuthentication? destinationMssqlSshTunnelMethodSshKeyAuthentication,

            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodNoTunnel? destinationMssqlUpdateSshTunnelMethodNoTunnel,

            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodPasswordAuthentication? destinationMssqlUpdateSshTunnelMethodPasswordAuthentication,

            Outputs.DestinationMSsqlConfigurationTunnelMethodDestinationMssqlUpdateSshTunnelMethodSshKeyAuthentication? destinationMssqlUpdateSshTunnelMethodSshKeyAuthentication)
        {
            DestinationMssqlSshTunnelMethodNoTunnel = destinationMssqlSshTunnelMethodNoTunnel;
            DestinationMssqlSshTunnelMethodPasswordAuthentication = destinationMssqlSshTunnelMethodPasswordAuthentication;
            DestinationMssqlSshTunnelMethodSshKeyAuthentication = destinationMssqlSshTunnelMethodSshKeyAuthentication;
            DestinationMssqlUpdateSshTunnelMethodNoTunnel = destinationMssqlUpdateSshTunnelMethodNoTunnel;
            DestinationMssqlUpdateSshTunnelMethodPasswordAuthentication = destinationMssqlUpdateSshTunnelMethodPasswordAuthentication;
            DestinationMssqlUpdateSshTunnelMethodSshKeyAuthentication = destinationMssqlUpdateSshTunnelMethodSshKeyAuthentication;
        }
    }
}
