// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetDestinationVerticaConfigurationTunnelMethodDestinationVerticaSshTunnelMethodPasswordAuthentication
    {
        public readonly string TunnelHost;
        public readonly string TunnelMethod;
        public readonly int TunnelPort;
        public readonly string TunnelUser;
        public readonly string TunnelUserPassword;

        [OutputConstructor]
        private GetDestinationVerticaConfigurationTunnelMethodDestinationVerticaSshTunnelMethodPasswordAuthentication(
            string tunnelHost,

            string tunnelMethod,

            int tunnelPort,

            string tunnelUser,

            string tunnelUserPassword)
        {
            TunnelHost = tunnelHost;
            TunnelMethod = tunnelMethod;
            TunnelPort = tunnelPort;
            TunnelUser = tunnelUser;
            TunnelUserPassword = tunnelUserPassword;
        }
    }
}
