// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetDestinationAWSDatalakeConfigurationFormat
    {
        public readonly Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson DestinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson;
        public readonly Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage DestinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage;
        public readonly Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson DestinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson;
        public readonly Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage DestinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage;

        [OutputConstructor]
        private GetDestinationAWSDatalakeConfigurationFormat(
            Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson destinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson,

            Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage destinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage,

            Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson destinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson,

            Outputs.GetDestinationAWSDatalakeConfigurationFormatDestinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage destinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage)
        {
            DestinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson = destinationAwsDatalakeOutputFormatWildcardJsonLinesNewlineDelimitedJson;
            DestinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage = destinationAwsDatalakeOutputFormatWildcardParquetColumnarStorage;
            DestinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson = destinationAwsDatalakeUpdateOutputFormatWildcardJsonLinesNewlineDelimitedJson;
            DestinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage = destinationAwsDatalakeUpdateOutputFormatWildcardParquetColumnarStorage;
        }
    }
}
