// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetDestinationElasticsearchConfigurationAuthenticationMethod
    {
        public readonly Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchAuthenticationMethodApiKeySecret DestinationElasticsearchAuthenticationMethodApiKeySecret;
        public readonly Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchAuthenticationMethodUsernamePassword DestinationElasticsearchAuthenticationMethodUsernamePassword;
        public readonly Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchUpdateAuthenticationMethodApiKeySecret DestinationElasticsearchUpdateAuthenticationMethodApiKeySecret;
        public readonly Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchUpdateAuthenticationMethodUsernamePassword DestinationElasticsearchUpdateAuthenticationMethodUsernamePassword;

        [OutputConstructor]
        private GetDestinationElasticsearchConfigurationAuthenticationMethod(
            Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchAuthenticationMethodApiKeySecret destinationElasticsearchAuthenticationMethodApiKeySecret,

            Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchAuthenticationMethodUsernamePassword destinationElasticsearchAuthenticationMethodUsernamePassword,

            Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchUpdateAuthenticationMethodApiKeySecret destinationElasticsearchUpdateAuthenticationMethodApiKeySecret,

            Outputs.GetDestinationElasticsearchConfigurationAuthenticationMethodDestinationElasticsearchUpdateAuthenticationMethodUsernamePassword destinationElasticsearchUpdateAuthenticationMethodUsernamePassword)
        {
            DestinationElasticsearchAuthenticationMethodApiKeySecret = destinationElasticsearchAuthenticationMethodApiKeySecret;
            DestinationElasticsearchAuthenticationMethodUsernamePassword = destinationElasticsearchAuthenticationMethodUsernamePassword;
            DestinationElasticsearchUpdateAuthenticationMethodApiKeySecret = destinationElasticsearchUpdateAuthenticationMethodApiKeySecret;
            DestinationElasticsearchUpdateAuthenticationMethodUsernamePassword = destinationElasticsearchUpdateAuthenticationMethodUsernamePassword;
        }
    }
}
