// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetDestinationAWSDatalakeConfigurationCredentialsDestinationAwsDatalakeAuthenticationModeIamUser
    {
        public readonly string AwsAccessKeyId;
        public readonly string AwsSecretAccessKey;
        public readonly string CredentialsTitle;

        [OutputConstructor]
        private GetDestinationAWSDatalakeConfigurationCredentialsDestinationAwsDatalakeAuthenticationModeIamUser(
            string awsAccessKeyId,

            string awsSecretAccessKey,

            string credentialsTitle)
        {
            AwsAccessKeyId = awsAccessKeyId;
            AwsSecretAccessKey = awsSecretAccessKey;
            CredentialsTitle = credentialsTitle;
        }
    }
}
