// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceOktaConfiguration
    {
        public readonly Outputs.GetSourceOktaConfigurationCredentials Credentials;
        public readonly string Domain;
        public readonly string SourceType;
        public readonly string StartDate;

        [OutputConstructor]
        private GetSourceOktaConfiguration(
            Outputs.GetSourceOktaConfigurationCredentials credentials,

            string domain,

            string sourceType,

            string startDate)
        {
            Credentials = credentials;
            Domain = domain;
            SourceType = sourceType;
            StartDate = startDate;
        }
    }
}
