// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceAircallConfiguration
    {
        public readonly string ApiId;
        public readonly string ApiToken;
        public readonly string SourceType;
        public readonly string StartDate;

        [OutputConstructor]
        private GetSourceAircallConfiguration(
            string apiId,

            string apiToken,

            string sourceType,

            string startDate)
        {
            ApiId = apiId;
            ApiToken = apiToken;
            SourceType = sourceType;
            StartDate = startDate;
        }
    }
}
