// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceGnewsConfiguration
    {
        public readonly string ApiKey;
        public readonly string Country;
        public readonly string EndDate;
        public readonly ImmutableArray<string> Ins;
        public readonly string Language;
        public readonly ImmutableArray<string> Nullables;
        public readonly string Query;
        public readonly string Sortby;
        public readonly string SourceType;
        public readonly string StartDate;
        public readonly string TopHeadlinesQuery;
        public readonly string TopHeadlinesTopic;

        [OutputConstructor]
        private GetSourceGnewsConfiguration(
            string apiKey,

            string country,

            string endDate,

            ImmutableArray<string> ins,

            string language,

            ImmutableArray<string> nullables,

            string query,

            string sortby,

            string sourceType,

            string startDate,

            string topHeadlinesQuery,

            string topHeadlinesTopic)
        {
            ApiKey = apiKey;
            Country = country;
            EndDate = endDate;
            Ins = ins;
            Language = language;
            Nullables = nullables;
            Query = query;
            Sortby = sortby;
            SourceType = sourceType;
            StartDate = startDate;
            TopHeadlinesQuery = topHeadlinesQuery;
            TopHeadlinesTopic = topHeadlinesTopic;
        }
    }
}
