// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourcePexelsApiConfiguration
    {
        public readonly string ApiKey;
        public readonly string Color;
        public readonly string Locale;
        public readonly string Orientation;
        public readonly string Query;
        public readonly string Size;
        public readonly string SourceType;

        [OutputConstructor]
        private GetSourcePexelsApiConfiguration(
            string apiKey,

            string color,

            string locale,

            string orientation,

            string query,

            string size,

            string sourceType)
        {
            ApiKey = apiKey;
            Color = color;
            Locale = locale;
            Orientation = orientation;
            Query = query;
            Size = size;
            SourceType = sourceType;
        }
    }
}
