// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceSentryConfiguration
    {
        public readonly string AuthToken;
        public readonly ImmutableArray<string> DiscoverFields;
        public readonly string Hostname;
        public readonly string Organization;
        public readonly string Project;
        public readonly string SourceType;

        [OutputConstructor]
        private GetSourceSentryConfiguration(
            string authToken,

            ImmutableArray<string> discoverFields,

            string hostname,

            string organization,

            string project,

            string sourceType)
        {
            AuthToken = authToken;
            DiscoverFields = discoverFields;
            Hostname = hostname;
            Organization = organization;
            Project = project;
            SourceType = sourceType;
        }
    }
}
