// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceLokaliseConfiguration
    {
        public readonly string ApiKey;
        public readonly string ProjectId;
        public readonly string SourceType;

        [OutputConstructor]
        private GetSourceLokaliseConfiguration(
            string apiKey,

            string projectId,

            string sourceType)
        {
            ApiKey = apiKey;
            ProjectId = projectId;
            SourceType = sourceType;
        }
    }
}
