// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class GetSourceSnowflakeConfigurationCredentials
    {
        public readonly Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeAuthorizationMethodOAuth20 SourceSnowflakeAuthorizationMethodOAuth20;
        public readonly Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeAuthorizationMethodUsernameAndPassword SourceSnowflakeAuthorizationMethodUsernameAndPassword;
        public readonly Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeUpdateAuthorizationMethodOAuth20 SourceSnowflakeUpdateAuthorizationMethodOAuth20;
        public readonly Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword SourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword;

        [OutputConstructor]
        private GetSourceSnowflakeConfigurationCredentials(
            Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeAuthorizationMethodOAuth20 sourceSnowflakeAuthorizationMethodOAuth20,

            Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeAuthorizationMethodUsernameAndPassword sourceSnowflakeAuthorizationMethodUsernameAndPassword,

            Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeUpdateAuthorizationMethodOAuth20 sourceSnowflakeUpdateAuthorizationMethodOAuth20,

            Outputs.GetSourceSnowflakeConfigurationCredentialsSourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword sourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword)
        {
            SourceSnowflakeAuthorizationMethodOAuth20 = sourceSnowflakeAuthorizationMethodOAuth20;
            SourceSnowflakeAuthorizationMethodUsernameAndPassword = sourceSnowflakeAuthorizationMethodUsernameAndPassword;
            SourceSnowflakeUpdateAuthorizationMethodOAuth20 = sourceSnowflakeUpdateAuthorizationMethodOAuth20;
            SourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword = sourceSnowflakeUpdateAuthorizationMethodUsernameAndPassword;
        }
    }
}
