// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceAzureTableConfiguration
    {
        public readonly string SourceType;
        public readonly string StorageAccessKey;
        public readonly string StorageAccountName;
        public readonly string? StorageEndpointSuffix;

        [OutputConstructor]
        private SourceAzureTableConfiguration(
            string sourceType,

            string storageAccessKey,

            string storageAccountName,

            string? storageEndpointSuffix)
        {
            SourceType = sourceType;
            StorageAccessKey = storageAccessKey;
            StorageAccountName = storageAccountName;
            StorageEndpointSuffix = storageEndpointSuffix;
        }
    }
}
