// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceSalesloftConfigurationCredentials
    {
        public readonly Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftCredentialsAuthenticateViaApiKey? SourceSalesloftCredentialsAuthenticateViaApiKey;
        public readonly Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftCredentialsAuthenticateViaOAuth? SourceSalesloftCredentialsAuthenticateViaOAuth;
        public readonly Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftUpdateCredentialsAuthenticateViaApiKey? SourceSalesloftUpdateCredentialsAuthenticateViaApiKey;
        public readonly Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftUpdateCredentialsAuthenticateViaOAuth? SourceSalesloftUpdateCredentialsAuthenticateViaOAuth;

        [OutputConstructor]
        private SourceSalesloftConfigurationCredentials(
            Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftCredentialsAuthenticateViaApiKey? sourceSalesloftCredentialsAuthenticateViaApiKey,

            Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftCredentialsAuthenticateViaOAuth? sourceSalesloftCredentialsAuthenticateViaOAuth,

            Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftUpdateCredentialsAuthenticateViaApiKey? sourceSalesloftUpdateCredentialsAuthenticateViaApiKey,

            Outputs.SourceSalesloftConfigurationCredentialsSourceSalesloftUpdateCredentialsAuthenticateViaOAuth? sourceSalesloftUpdateCredentialsAuthenticateViaOAuth)
        {
            SourceSalesloftCredentialsAuthenticateViaApiKey = sourceSalesloftCredentialsAuthenticateViaApiKey;
            SourceSalesloftCredentialsAuthenticateViaOAuth = sourceSalesloftCredentialsAuthenticateViaOAuth;
            SourceSalesloftUpdateCredentialsAuthenticateViaApiKey = sourceSalesloftUpdateCredentialsAuthenticateViaApiKey;
            SourceSalesloftUpdateCredentialsAuthenticateViaOAuth = sourceSalesloftUpdateCredentialsAuthenticateViaOAuth;
        }
    }
}
