// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceLeverHiring DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceLeverHiring(ctx, &airbyte.LookupSourceLeverHiringArgs{
//				SecretId: pulumi.StringRef("...my_secret_id..."),
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceLeverHiring(ctx *pulumi.Context, args *LookupSourceLeverHiringArgs, opts ...pulumi.InvokeOption) (*LookupSourceLeverHiringResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceLeverHiringResult
	err := ctx.Invoke("airbyte:index/getSourceLeverHiring:getSourceLeverHiring", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceLeverHiring.
type LookupSourceLeverHiringArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId *string `pulumi:"secretId"`
	SourceId string  `pulumi:"sourceId"`
}

// A collection of values returned by getSourceLeverHiring.
type LookupSourceLeverHiringResult struct {
	Configuration GetSourceLeverHiringConfiguration `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    string  `pulumi:"sourceId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

func LookupSourceLeverHiringOutput(ctx *pulumi.Context, args LookupSourceLeverHiringOutputArgs, opts ...pulumi.InvokeOption) LookupSourceLeverHiringResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceLeverHiringResult, error) {
			args := v.(LookupSourceLeverHiringArgs)
			r, err := LookupSourceLeverHiring(ctx, &args, opts...)
			var s LookupSourceLeverHiringResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceLeverHiringResultOutput)
}

// A collection of arguments for invoking getSourceLeverHiring.
type LookupSourceLeverHiringOutputArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId pulumi.StringPtrInput `pulumi:"secretId"`
	SourceId pulumi.StringInput    `pulumi:"sourceId"`
}

func (LookupSourceLeverHiringOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceLeverHiringArgs)(nil)).Elem()
}

// A collection of values returned by getSourceLeverHiring.
type LookupSourceLeverHiringResultOutput struct{ *pulumi.OutputState }

func (LookupSourceLeverHiringResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceLeverHiringResult)(nil)).Elem()
}

func (o LookupSourceLeverHiringResultOutput) ToLookupSourceLeverHiringResultOutput() LookupSourceLeverHiringResultOutput {
	return o
}

func (o LookupSourceLeverHiringResultOutput) ToLookupSourceLeverHiringResultOutputWithContext(ctx context.Context) LookupSourceLeverHiringResultOutput {
	return o
}

func (o LookupSourceLeverHiringResultOutput) Configuration() GetSourceLeverHiringConfigurationOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) GetSourceLeverHiringConfiguration { return v.Configuration }).(GetSourceLeverHiringConfigurationOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceLeverHiringResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceLeverHiringResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) string { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o LookupSourceLeverHiringResultOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) *string { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o LookupSourceLeverHiringResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceLeverHiringResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceLeverHiringResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceLeverHiringResultOutput{})
}
