// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceAzureBlobStorage DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceAzureBlobStorage(ctx, &airbyte.LookupSourceAzureBlobStorageArgs{
//				SecretId: pulumi.StringRef("...my_secret_id..."),
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceAzureBlobStorage(ctx *pulumi.Context, args *LookupSourceAzureBlobStorageArgs, opts ...pulumi.InvokeOption) (*LookupSourceAzureBlobStorageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceAzureBlobStorageResult
	err := ctx.Invoke("airbyte:index/getSourceAzureBlobStorage:getSourceAzureBlobStorage", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceAzureBlobStorage.
type LookupSourceAzureBlobStorageArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId *string `pulumi:"secretId"`
	SourceId string  `pulumi:"sourceId"`
}

// A collection of values returned by getSourceAzureBlobStorage.
type LookupSourceAzureBlobStorageResult struct {
	Configuration GetSourceAzureBlobStorageConfiguration `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    string  `pulumi:"sourceId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

func LookupSourceAzureBlobStorageOutput(ctx *pulumi.Context, args LookupSourceAzureBlobStorageOutputArgs, opts ...pulumi.InvokeOption) LookupSourceAzureBlobStorageResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceAzureBlobStorageResult, error) {
			args := v.(LookupSourceAzureBlobStorageArgs)
			r, err := LookupSourceAzureBlobStorage(ctx, &args, opts...)
			var s LookupSourceAzureBlobStorageResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceAzureBlobStorageResultOutput)
}

// A collection of arguments for invoking getSourceAzureBlobStorage.
type LookupSourceAzureBlobStorageOutputArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId pulumi.StringPtrInput `pulumi:"secretId"`
	SourceId pulumi.StringInput    `pulumi:"sourceId"`
}

func (LookupSourceAzureBlobStorageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceAzureBlobStorageArgs)(nil)).Elem()
}

// A collection of values returned by getSourceAzureBlobStorage.
type LookupSourceAzureBlobStorageResultOutput struct{ *pulumi.OutputState }

func (LookupSourceAzureBlobStorageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceAzureBlobStorageResult)(nil)).Elem()
}

func (o LookupSourceAzureBlobStorageResultOutput) ToLookupSourceAzureBlobStorageResultOutput() LookupSourceAzureBlobStorageResultOutput {
	return o
}

func (o LookupSourceAzureBlobStorageResultOutput) ToLookupSourceAzureBlobStorageResultOutputWithContext(ctx context.Context) LookupSourceAzureBlobStorageResultOutput {
	return o
}

func (o LookupSourceAzureBlobStorageResultOutput) Configuration() GetSourceAzureBlobStorageConfigurationOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) GetSourceAzureBlobStorageConfiguration {
		return v.Configuration
	}).(GetSourceAzureBlobStorageConfigurationOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceAzureBlobStorageResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceAzureBlobStorageResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) string { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o LookupSourceAzureBlobStorageResultOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) *string { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o LookupSourceAzureBlobStorageResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceAzureBlobStorageResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAzureBlobStorageResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceAzureBlobStorageResultOutput{})
}
