// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-airbyte/sdk/go/airbyte/internal"
)

// SourceConfigcat DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-airbyte/sdk/go/airbyte"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceConfigcat(ctx, &airbyte.LookupSourceConfigcatArgs{
//				SecretId: pulumi.StringRef("...my_secret_id..."),
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceConfigcat(ctx *pulumi.Context, args *LookupSourceConfigcatArgs, opts ...pulumi.InvokeOption) (*LookupSourceConfigcatResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceConfigcatResult
	err := ctx.Invoke("airbyte:index/getSourceConfigcat:getSourceConfigcat", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceConfigcat.
type LookupSourceConfigcatArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId *string `pulumi:"secretId"`
	SourceId string  `pulumi:"sourceId"`
}

// A collection of values returned by getSourceConfigcat.
type LookupSourceConfigcatResult struct {
	Configuration GetSourceConfigcatConfiguration `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    string  `pulumi:"sourceId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

func LookupSourceConfigcatOutput(ctx *pulumi.Context, args LookupSourceConfigcatOutputArgs, opts ...pulumi.InvokeOption) LookupSourceConfigcatResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceConfigcatResult, error) {
			args := v.(LookupSourceConfigcatArgs)
			r, err := LookupSourceConfigcat(ctx, &args, opts...)
			var s LookupSourceConfigcatResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceConfigcatResultOutput)
}

// A collection of arguments for invoking getSourceConfigcat.
type LookupSourceConfigcatOutputArgs struct {
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId pulumi.StringPtrInput `pulumi:"secretId"`
	SourceId pulumi.StringInput    `pulumi:"sourceId"`
}

func (LookupSourceConfigcatOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceConfigcatArgs)(nil)).Elem()
}

// A collection of values returned by getSourceConfigcat.
type LookupSourceConfigcatResultOutput struct{ *pulumi.OutputState }

func (LookupSourceConfigcatResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceConfigcatResult)(nil)).Elem()
}

func (o LookupSourceConfigcatResultOutput) ToLookupSourceConfigcatResultOutput() LookupSourceConfigcatResultOutput {
	return o
}

func (o LookupSourceConfigcatResultOutput) ToLookupSourceConfigcatResultOutputWithContext(ctx context.Context) LookupSourceConfigcatResultOutput {
	return o
}

func (o LookupSourceConfigcatResultOutput) Configuration() GetSourceConfigcatConfigurationOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) GetSourceConfigcatConfiguration { return v.Configuration }).(GetSourceConfigcatConfigurationOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceConfigcatResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceConfigcatResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) string { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o LookupSourceConfigcatResultOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) *string { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o LookupSourceConfigcatResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceConfigcatResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceConfigcatResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceConfigcatResultOutput{})
}
