// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SourceLemlist struct {
	pulumi.CustomResourceState

	Configuration SourceLemlistConfigurationOutput `pulumi:"configuration"`
	Name          pulumi.StringOutput              `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceLemlist registers a new resource with the given unique name, arguments, and options.
func NewSourceLemlist(ctx *pulumi.Context,
	name string, args *SourceLemlistArgs, opts ...pulumi.ResourceOption) (*SourceLemlist, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	var resource SourceLemlist
	err := ctx.RegisterResource("airbyte:index/sourceLemlist:SourceLemlist", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceLemlist gets an existing SourceLemlist resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceLemlist(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceLemlistState, opts ...pulumi.ResourceOption) (*SourceLemlist, error) {
	var resource SourceLemlist
	err := ctx.ReadResource("airbyte:index/sourceLemlist:SourceLemlist", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceLemlist resources.
type sourceLemlistState struct {
	Configuration *SourceLemlistConfiguration `pulumi:"configuration"`
	Name          *string                     `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceLemlistState struct {
	Configuration SourceLemlistConfigurationPtrInput
	Name          pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceLemlistState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceLemlistState)(nil)).Elem()
}

type sourceLemlistArgs struct {
	Configuration SourceLemlistConfiguration `pulumi:"configuration"`
	Name          string                     `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceLemlist resource.
type SourceLemlistArgs struct {
	Configuration SourceLemlistConfigurationInput
	Name          pulumi.StringInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceLemlistArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceLemlistArgs)(nil)).Elem()
}

type SourceLemlistInput interface {
	pulumi.Input

	ToSourceLemlistOutput() SourceLemlistOutput
	ToSourceLemlistOutputWithContext(ctx context.Context) SourceLemlistOutput
}

func (*SourceLemlist) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceLemlist)(nil)).Elem()
}

func (i *SourceLemlist) ToSourceLemlistOutput() SourceLemlistOutput {
	return i.ToSourceLemlistOutputWithContext(context.Background())
}

func (i *SourceLemlist) ToSourceLemlistOutputWithContext(ctx context.Context) SourceLemlistOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceLemlistOutput)
}

type SourceLemlistOutput struct{ *pulumi.OutputState }

func (SourceLemlistOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceLemlist)(nil)).Elem()
}

func (o SourceLemlistOutput) ToSourceLemlistOutput() SourceLemlistOutput {
	return o
}

func (o SourceLemlistOutput) ToSourceLemlistOutputWithContext(ctx context.Context) SourceLemlistOutput {
	return o
}

func (o SourceLemlistOutput) Configuration() SourceLemlistConfigurationOutput {
	return o.ApplyT(func(v *SourceLemlist) SourceLemlistConfigurationOutput { return v.Configuration }).(SourceLemlistConfigurationOutput)
}

func (o SourceLemlistOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceLemlist) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o SourceLemlistOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceLemlist) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceLemlistOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceLemlist) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceLemlistOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceLemlist) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceLemlistOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceLemlist) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceLemlistInput)(nil)).Elem(), &SourceLemlist{})
	pulumi.RegisterOutputType(SourceLemlistOutput{})
}
