// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SourceSendinblue struct {
	pulumi.CustomResourceState

	Configuration SourceSendinblueConfigurationOutput `pulumi:"configuration"`
	Name          pulumi.StringOutput                 `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceSendinblue registers a new resource with the given unique name, arguments, and options.
func NewSourceSendinblue(ctx *pulumi.Context,
	name string, args *SourceSendinblueArgs, opts ...pulumi.ResourceOption) (*SourceSendinblue, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	var resource SourceSendinblue
	err := ctx.RegisterResource("airbyte:index/sourceSendinblue:SourceSendinblue", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceSendinblue gets an existing SourceSendinblue resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceSendinblue(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceSendinblueState, opts ...pulumi.ResourceOption) (*SourceSendinblue, error) {
	var resource SourceSendinblue
	err := ctx.ReadResource("airbyte:index/sourceSendinblue:SourceSendinblue", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceSendinblue resources.
type sourceSendinblueState struct {
	Configuration *SourceSendinblueConfiguration `pulumi:"configuration"`
	Name          *string                        `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceSendinblueState struct {
	Configuration SourceSendinblueConfigurationPtrInput
	Name          pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceSendinblueState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceSendinblueState)(nil)).Elem()
}

type sourceSendinblueArgs struct {
	Configuration SourceSendinblueConfiguration `pulumi:"configuration"`
	Name          string                        `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceSendinblue resource.
type SourceSendinblueArgs struct {
	Configuration SourceSendinblueConfigurationInput
	Name          pulumi.StringInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceSendinblueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceSendinblueArgs)(nil)).Elem()
}

type SourceSendinblueInput interface {
	pulumi.Input

	ToSourceSendinblueOutput() SourceSendinblueOutput
	ToSourceSendinblueOutputWithContext(ctx context.Context) SourceSendinblueOutput
}

func (*SourceSendinblue) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceSendinblue)(nil)).Elem()
}

func (i *SourceSendinblue) ToSourceSendinblueOutput() SourceSendinblueOutput {
	return i.ToSourceSendinblueOutputWithContext(context.Background())
}

func (i *SourceSendinblue) ToSourceSendinblueOutputWithContext(ctx context.Context) SourceSendinblueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceSendinblueOutput)
}

type SourceSendinblueOutput struct{ *pulumi.OutputState }

func (SourceSendinblueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceSendinblue)(nil)).Elem()
}

func (o SourceSendinblueOutput) ToSourceSendinblueOutput() SourceSendinblueOutput {
	return o
}

func (o SourceSendinblueOutput) ToSourceSendinblueOutputWithContext(ctx context.Context) SourceSendinblueOutput {
	return o
}

func (o SourceSendinblueOutput) Configuration() SourceSendinblueConfigurationOutput {
	return o.ApplyT(func(v *SourceSendinblue) SourceSendinblueConfigurationOutput { return v.Configuration }).(SourceSendinblueConfigurationOutput)
}

func (o SourceSendinblueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSendinblue) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o SourceSendinblueOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceSendinblue) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceSendinblueOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSendinblue) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceSendinblueOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSendinblue) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceSendinblueOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSendinblue) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceSendinblueInput)(nil)).Elem(), &SourceSendinblue{})
	pulumi.RegisterOutputType(SourceSendinblueOutput{})
}
