// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SourceSenseforce struct {
	pulumi.CustomResourceState

	Configuration SourceSenseforceConfigurationOutput `pulumi:"configuration"`
	Name          pulumi.StringOutput                 `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceSenseforce registers a new resource with the given unique name, arguments, and options.
func NewSourceSenseforce(ctx *pulumi.Context,
	name string, args *SourceSenseforceArgs, opts ...pulumi.ResourceOption) (*SourceSenseforce, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource SourceSenseforce
	err := ctx.RegisterResource("airbyte:index/sourceSenseforce:SourceSenseforce", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceSenseforce gets an existing SourceSenseforce resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceSenseforce(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceSenseforceState, opts ...pulumi.ResourceOption) (*SourceSenseforce, error) {
	var resource SourceSenseforce
	err := ctx.ReadResource("airbyte:index/sourceSenseforce:SourceSenseforce", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceSenseforce resources.
type sourceSenseforceState struct {
	Configuration *SourceSenseforceConfiguration `pulumi:"configuration"`
	Name          *string                        `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceSenseforceState struct {
	Configuration SourceSenseforceConfigurationPtrInput
	Name          pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceSenseforceState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceSenseforceState)(nil)).Elem()
}

type sourceSenseforceArgs struct {
	Configuration SourceSenseforceConfiguration `pulumi:"configuration"`
	Name          string                        `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceSenseforce resource.
type SourceSenseforceArgs struct {
	Configuration SourceSenseforceConfigurationInput
	Name          pulumi.StringInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceSenseforceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceSenseforceArgs)(nil)).Elem()
}

type SourceSenseforceInput interface {
	pulumi.Input

	ToSourceSenseforceOutput() SourceSenseforceOutput
	ToSourceSenseforceOutputWithContext(ctx context.Context) SourceSenseforceOutput
}

func (*SourceSenseforce) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceSenseforce)(nil)).Elem()
}

func (i *SourceSenseforce) ToSourceSenseforceOutput() SourceSenseforceOutput {
	return i.ToSourceSenseforceOutputWithContext(context.Background())
}

func (i *SourceSenseforce) ToSourceSenseforceOutputWithContext(ctx context.Context) SourceSenseforceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceSenseforceOutput)
}

type SourceSenseforceOutput struct{ *pulumi.OutputState }

func (SourceSenseforceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceSenseforce)(nil)).Elem()
}

func (o SourceSenseforceOutput) ToSourceSenseforceOutput() SourceSenseforceOutput {
	return o
}

func (o SourceSenseforceOutput) ToSourceSenseforceOutputWithContext(ctx context.Context) SourceSenseforceOutput {
	return o
}

func (o SourceSenseforceOutput) Configuration() SourceSenseforceConfigurationOutput {
	return o.ApplyT(func(v *SourceSenseforce) SourceSenseforceConfigurationOutput { return v.Configuration }).(SourceSenseforceConfigurationOutput)
}

func (o SourceSenseforceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSenseforce) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o SourceSenseforceOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceSenseforce) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceSenseforceOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSenseforce) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceSenseforceOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSenseforce) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceSenseforceOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceSenseforce) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceSenseforceInput)(nil)).Elem(), &SourceSenseforce{})
	pulumi.RegisterOutputType(SourceSenseforceOutput{})
}
