// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-airbyte/sdk/go/airbyte/internal"
)

// SourceMongodbInternalPoc Resource
type SourceMongodbInternalPoc struct {
	pulumi.CustomResourceState

	Configuration SourceMongodbInternalPocConfigurationOutput `pulumi:"configuration"`
	Name          pulumi.StringOutput                         `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceMongodbInternalPoc registers a new resource with the given unique name, arguments, and options.
func NewSourceMongodbInternalPoc(ctx *pulumi.Context,
	name string, args *SourceMongodbInternalPocArgs, opts ...pulumi.ResourceOption) (*SourceMongodbInternalPoc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SourceMongodbInternalPoc
	err := ctx.RegisterResource("airbyte:index/sourceMongodbInternalPoc:SourceMongodbInternalPoc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceMongodbInternalPoc gets an existing SourceMongodbInternalPoc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceMongodbInternalPoc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceMongodbInternalPocState, opts ...pulumi.ResourceOption) (*SourceMongodbInternalPoc, error) {
	var resource SourceMongodbInternalPoc
	err := ctx.ReadResource("airbyte:index/sourceMongodbInternalPoc:SourceMongodbInternalPoc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceMongodbInternalPoc resources.
type sourceMongodbInternalPocState struct {
	Configuration *SourceMongodbInternalPocConfiguration `pulumi:"configuration"`
	Name          *string                                `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceMongodbInternalPocState struct {
	Configuration SourceMongodbInternalPocConfigurationPtrInput
	Name          pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceMongodbInternalPocState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceMongodbInternalPocState)(nil)).Elem()
}

type sourceMongodbInternalPocArgs struct {
	Configuration SourceMongodbInternalPocConfiguration `pulumi:"configuration"`
	Name          string                                `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceMongodbInternalPoc resource.
type SourceMongodbInternalPocArgs struct {
	Configuration SourceMongodbInternalPocConfigurationInput
	Name          pulumi.StringInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceMongodbInternalPocArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceMongodbInternalPocArgs)(nil)).Elem()
}

type SourceMongodbInternalPocInput interface {
	pulumi.Input

	ToSourceMongodbInternalPocOutput() SourceMongodbInternalPocOutput
	ToSourceMongodbInternalPocOutputWithContext(ctx context.Context) SourceMongodbInternalPocOutput
}

func (*SourceMongodbInternalPoc) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceMongodbInternalPoc)(nil)).Elem()
}

func (i *SourceMongodbInternalPoc) ToSourceMongodbInternalPocOutput() SourceMongodbInternalPocOutput {
	return i.ToSourceMongodbInternalPocOutputWithContext(context.Background())
}

func (i *SourceMongodbInternalPoc) ToSourceMongodbInternalPocOutputWithContext(ctx context.Context) SourceMongodbInternalPocOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceMongodbInternalPocOutput)
}

// SourceMongodbInternalPocArrayInput is an input type that accepts SourceMongodbInternalPocArray and SourceMongodbInternalPocArrayOutput values.
// You can construct a concrete instance of `SourceMongodbInternalPocArrayInput` via:
//
//	SourceMongodbInternalPocArray{ SourceMongodbInternalPocArgs{...} }
type SourceMongodbInternalPocArrayInput interface {
	pulumi.Input

	ToSourceMongodbInternalPocArrayOutput() SourceMongodbInternalPocArrayOutput
	ToSourceMongodbInternalPocArrayOutputWithContext(context.Context) SourceMongodbInternalPocArrayOutput
}

type SourceMongodbInternalPocArray []SourceMongodbInternalPocInput

func (SourceMongodbInternalPocArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceMongodbInternalPoc)(nil)).Elem()
}

func (i SourceMongodbInternalPocArray) ToSourceMongodbInternalPocArrayOutput() SourceMongodbInternalPocArrayOutput {
	return i.ToSourceMongodbInternalPocArrayOutputWithContext(context.Background())
}

func (i SourceMongodbInternalPocArray) ToSourceMongodbInternalPocArrayOutputWithContext(ctx context.Context) SourceMongodbInternalPocArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceMongodbInternalPocArrayOutput)
}

// SourceMongodbInternalPocMapInput is an input type that accepts SourceMongodbInternalPocMap and SourceMongodbInternalPocMapOutput values.
// You can construct a concrete instance of `SourceMongodbInternalPocMapInput` via:
//
//	SourceMongodbInternalPocMap{ "key": SourceMongodbInternalPocArgs{...} }
type SourceMongodbInternalPocMapInput interface {
	pulumi.Input

	ToSourceMongodbInternalPocMapOutput() SourceMongodbInternalPocMapOutput
	ToSourceMongodbInternalPocMapOutputWithContext(context.Context) SourceMongodbInternalPocMapOutput
}

type SourceMongodbInternalPocMap map[string]SourceMongodbInternalPocInput

func (SourceMongodbInternalPocMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceMongodbInternalPoc)(nil)).Elem()
}

func (i SourceMongodbInternalPocMap) ToSourceMongodbInternalPocMapOutput() SourceMongodbInternalPocMapOutput {
	return i.ToSourceMongodbInternalPocMapOutputWithContext(context.Background())
}

func (i SourceMongodbInternalPocMap) ToSourceMongodbInternalPocMapOutputWithContext(ctx context.Context) SourceMongodbInternalPocMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceMongodbInternalPocMapOutput)
}

type SourceMongodbInternalPocOutput struct{ *pulumi.OutputState }

func (SourceMongodbInternalPocOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceMongodbInternalPoc)(nil)).Elem()
}

func (o SourceMongodbInternalPocOutput) ToSourceMongodbInternalPocOutput() SourceMongodbInternalPocOutput {
	return o
}

func (o SourceMongodbInternalPocOutput) ToSourceMongodbInternalPocOutputWithContext(ctx context.Context) SourceMongodbInternalPocOutput {
	return o
}

func (o SourceMongodbInternalPocOutput) Configuration() SourceMongodbInternalPocConfigurationOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) SourceMongodbInternalPocConfigurationOutput { return v.Configuration }).(SourceMongodbInternalPocConfigurationOutput)
}

func (o SourceMongodbInternalPocOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o SourceMongodbInternalPocOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceMongodbInternalPocOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceMongodbInternalPocOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceMongodbInternalPocOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceMongodbInternalPoc) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

type SourceMongodbInternalPocArrayOutput struct{ *pulumi.OutputState }

func (SourceMongodbInternalPocArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceMongodbInternalPoc)(nil)).Elem()
}

func (o SourceMongodbInternalPocArrayOutput) ToSourceMongodbInternalPocArrayOutput() SourceMongodbInternalPocArrayOutput {
	return o
}

func (o SourceMongodbInternalPocArrayOutput) ToSourceMongodbInternalPocArrayOutputWithContext(ctx context.Context) SourceMongodbInternalPocArrayOutput {
	return o
}

func (o SourceMongodbInternalPocArrayOutput) Index(i pulumi.IntInput) SourceMongodbInternalPocOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SourceMongodbInternalPoc {
		return vs[0].([]*SourceMongodbInternalPoc)[vs[1].(int)]
	}).(SourceMongodbInternalPocOutput)
}

type SourceMongodbInternalPocMapOutput struct{ *pulumi.OutputState }

func (SourceMongodbInternalPocMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceMongodbInternalPoc)(nil)).Elem()
}

func (o SourceMongodbInternalPocMapOutput) ToSourceMongodbInternalPocMapOutput() SourceMongodbInternalPocMapOutput {
	return o
}

func (o SourceMongodbInternalPocMapOutput) ToSourceMongodbInternalPocMapOutputWithContext(ctx context.Context) SourceMongodbInternalPocMapOutput {
	return o
}

func (o SourceMongodbInternalPocMapOutput) MapIndex(k pulumi.StringInput) SourceMongodbInternalPocOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SourceMongodbInternalPoc {
		return vs[0].(map[string]*SourceMongodbInternalPoc)[vs[1].(string)]
	}).(SourceMongodbInternalPocOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceMongodbInternalPocInput)(nil)).Elem(), &SourceMongodbInternalPoc{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceMongodbInternalPocArrayInput)(nil)).Elem(), SourceMongodbInternalPocArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceMongodbInternalPocMapInput)(nil)).Elem(), SourceMongodbInternalPocMap{})
	pulumi.RegisterOutputType(SourceMongodbInternalPocOutput{})
	pulumi.RegisterOutputType(SourceMongodbInternalPocArrayOutput{})
	pulumi.RegisterOutputType(SourceMongodbInternalPocMapOutput{})
}
