// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceDelighted Resource
type SourceDelighted struct {
	pulumi.CustomResourceState

	Configuration SourceDelightedConfigurationOutput `pulumi:"configuration"`
	Name          pulumi.StringOutput                `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceDelighted registers a new resource with the given unique name, arguments, and options.
func NewSourceDelighted(ctx *pulumi.Context,
	name string, args *SourceDelightedArgs, opts ...pulumi.ResourceOption) (*SourceDelighted, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SourceDelighted
	err := ctx.RegisterResource("airbyte:index/sourceDelighted:SourceDelighted", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceDelighted gets an existing SourceDelighted resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceDelighted(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceDelightedState, opts ...pulumi.ResourceOption) (*SourceDelighted, error) {
	var resource SourceDelighted
	err := ctx.ReadResource("airbyte:index/sourceDelighted:SourceDelighted", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceDelighted resources.
type sourceDelightedState struct {
	Configuration *SourceDelightedConfiguration `pulumi:"configuration"`
	Name          *string                       `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceDelightedState struct {
	Configuration SourceDelightedConfigurationPtrInput
	Name          pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceDelightedState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceDelightedState)(nil)).Elem()
}

type sourceDelightedArgs struct {
	Configuration SourceDelightedConfiguration `pulumi:"configuration"`
	Name          string                       `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceDelighted resource.
type SourceDelightedArgs struct {
	Configuration SourceDelightedConfigurationInput
	Name          pulumi.StringInput
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceDelightedArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceDelightedArgs)(nil)).Elem()
}

type SourceDelightedInput interface {
	pulumi.Input

	ToSourceDelightedOutput() SourceDelightedOutput
	ToSourceDelightedOutputWithContext(ctx context.Context) SourceDelightedOutput
}

func (*SourceDelighted) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceDelighted)(nil)).Elem()
}

func (i *SourceDelighted) ToSourceDelightedOutput() SourceDelightedOutput {
	return i.ToSourceDelightedOutputWithContext(context.Background())
}

func (i *SourceDelighted) ToSourceDelightedOutputWithContext(ctx context.Context) SourceDelightedOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceDelightedOutput)
}

// SourceDelightedArrayInput is an input type that accepts SourceDelightedArray and SourceDelightedArrayOutput values.
// You can construct a concrete instance of `SourceDelightedArrayInput` via:
//
//	SourceDelightedArray{ SourceDelightedArgs{...} }
type SourceDelightedArrayInput interface {
	pulumi.Input

	ToSourceDelightedArrayOutput() SourceDelightedArrayOutput
	ToSourceDelightedArrayOutputWithContext(context.Context) SourceDelightedArrayOutput
}

type SourceDelightedArray []SourceDelightedInput

func (SourceDelightedArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceDelighted)(nil)).Elem()
}

func (i SourceDelightedArray) ToSourceDelightedArrayOutput() SourceDelightedArrayOutput {
	return i.ToSourceDelightedArrayOutputWithContext(context.Background())
}

func (i SourceDelightedArray) ToSourceDelightedArrayOutputWithContext(ctx context.Context) SourceDelightedArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceDelightedArrayOutput)
}

// SourceDelightedMapInput is an input type that accepts SourceDelightedMap and SourceDelightedMapOutput values.
// You can construct a concrete instance of `SourceDelightedMapInput` via:
//
//	SourceDelightedMap{ "key": SourceDelightedArgs{...} }
type SourceDelightedMapInput interface {
	pulumi.Input

	ToSourceDelightedMapOutput() SourceDelightedMapOutput
	ToSourceDelightedMapOutputWithContext(context.Context) SourceDelightedMapOutput
}

type SourceDelightedMap map[string]SourceDelightedInput

func (SourceDelightedMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceDelighted)(nil)).Elem()
}

func (i SourceDelightedMap) ToSourceDelightedMapOutput() SourceDelightedMapOutput {
	return i.ToSourceDelightedMapOutputWithContext(context.Background())
}

func (i SourceDelightedMap) ToSourceDelightedMapOutputWithContext(ctx context.Context) SourceDelightedMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceDelightedMapOutput)
}

type SourceDelightedOutput struct{ *pulumi.OutputState }

func (SourceDelightedOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceDelighted)(nil)).Elem()
}

func (o SourceDelightedOutput) ToSourceDelightedOutput() SourceDelightedOutput {
	return o
}

func (o SourceDelightedOutput) ToSourceDelightedOutputWithContext(ctx context.Context) SourceDelightedOutput {
	return o
}

func (o SourceDelightedOutput) Configuration() SourceDelightedConfigurationOutput {
	return o.ApplyT(func(v *SourceDelighted) SourceDelightedConfigurationOutput { return v.Configuration }).(SourceDelightedConfigurationOutput)
}

func (o SourceDelightedOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceDelighted) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow.
func (o SourceDelightedOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceDelighted) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceDelightedOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceDelighted) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceDelightedOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceDelighted) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceDelightedOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceDelighted) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

type SourceDelightedArrayOutput struct{ *pulumi.OutputState }

func (SourceDelightedArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceDelighted)(nil)).Elem()
}

func (o SourceDelightedArrayOutput) ToSourceDelightedArrayOutput() SourceDelightedArrayOutput {
	return o
}

func (o SourceDelightedArrayOutput) ToSourceDelightedArrayOutputWithContext(ctx context.Context) SourceDelightedArrayOutput {
	return o
}

func (o SourceDelightedArrayOutput) Index(i pulumi.IntInput) SourceDelightedOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SourceDelighted {
		return vs[0].([]*SourceDelighted)[vs[1].(int)]
	}).(SourceDelightedOutput)
}

type SourceDelightedMapOutput struct{ *pulumi.OutputState }

func (SourceDelightedMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceDelighted)(nil)).Elem()
}

func (o SourceDelightedMapOutput) ToSourceDelightedMapOutput() SourceDelightedMapOutput {
	return o
}

func (o SourceDelightedMapOutput) ToSourceDelightedMapOutputWithContext(ctx context.Context) SourceDelightedMapOutput {
	return o
}

func (o SourceDelightedMapOutput) MapIndex(k pulumi.StringInput) SourceDelightedOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SourceDelighted {
		return vs[0].(map[string]*SourceDelighted)[vs[1].(string)]
	}).(SourceDelightedOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceDelightedInput)(nil)).Elem(), &SourceDelighted{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceDelightedArrayInput)(nil)).Elem(), SourceDelightedArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceDelightedMapInput)(nil)).Elem(), SourceDelightedMap{})
	pulumi.RegisterOutputType(SourceDelightedOutput{})
	pulumi.RegisterOutputType(SourceDelightedArrayOutput{})
	pulumi.RegisterOutputType(SourceDelightedMapOutput{})
}
