// Copyright 2016-2018, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package airbyte

import (
	// embed is used to store bridge-metadata.json in the compiled binary
	_ "embed"
	"fmt"
	"path/filepath"
	"unicode"

	// "github.com/hashicorp/terraform-plugin-framework/provider"
	pf "github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge"
	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge"
	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"

	"github.com/ryan-pip/pulumi-airbyte/provider/pkg/version"
	"github.com/ryan-pip/terraform-provider-airbyte/shim"
)

// all of the airbyte token components used below.
const (
	airbytePkg = "airbyte"
	airbyteMod = "index"
)

// airbyteMember manufactures a type token for the airbyte package and the given module and type.
func airbyteMember(mod string, mem string) tokens.ModuleMember {
	return tokens.ModuleMember(airbytePkg + ":" + mod + ":" + mem)
}

// airbyteType manufactures a type token for the airbyte package and the given module and type.
func airbyteType(mod string, typ string) tokens.Type {
	return tokens.Type(airbyteMember(mod, typ))
}

func airbyteDataSource(mod string, res string) tokens.ModuleMember {
	fn := string(unicode.ToLower(rune(res[0]))) + res[1:]
	return airbyteMember(mod+"/"+fn, res)
}

// airbyteResource manufactures a standard resource token given a module and resource name.  It automatically uses the
// airbyte package and names the file by simply lower casing the resource's first character.
func airbyteResource(mod string, res string) tokens.Type {
	fn := string(unicode.ToLower(rune(res[0]))) + res[1:]
	return airbyteType(mod+"/"+fn, res)
}

//go:embed cmd/pulumi-resource-airbyte/bridge-metadata.json
var bridgeMetadata []byte

func Provider() tfbridge.ProviderInfo {
	info := tfbridge.ProviderInfo{
		P:           pf.ShimProvider(shim.NewProvider()),
		Name:        "airbyte",
		DisplayName: "Airbyte",
		Publisher:   "Pulumi",
		// LogoURL is optional but useful to help identify your package in the Pulumi Registry
		// if this package is published there.
		//
		// You may host a logo on a domain you control or add an SVG logo for your package
		// in your repository and use the raw content URL for that file as your logo URL.
		LogoURL: "",
		// PluginDownloadURL is an optional URL used to download the Provider
		// for use in Pulumi programs
		// e.g https://github.com/org/pulumi-provider-name/releases/
		PluginDownloadURL: "github://api.github.com/ryan-pip",
		Description:       "A Pulumi package for creating and managing xyz cloud resources.",
		// category/cloud tag helps with categorizing the package in the Pulumi Registry.
		// For all available categories, see `Keywords` in
		// https://www.pulumi.com/docs/guides/pulumi-packages/schema/#package.
		Keywords:   []string{"pulumi", "airbyte", "category/utility"},
		License:    "Apache-2.0",
		Homepage:   "https://www.airbyte.com",
		Repository: "https://github.com/ryan-pip/pulumi-airbyte",
		// The GitHub Org for the provider - defaults to `terraform-providers`. Note that this
		// should match the TF provider module's require directive, not any replace directives.
		GitHubOrg:    "ryan-pip",
		MetadataInfo: tfbridge.NewProviderMetadata(bridgeMetadata),
		Config: map[string]*tfbridge.SchemaInfo{
			"server_url": {
				Default: &tfbridge.DefaultInfo{
					Value:   "https://api.airbyte.com/v1",
					EnvVars: []string{"AIRBYTE_SERVER_URL"},
				},
				MarkAsOptional: tfbridge.True(),
			},
			"password": {
				Default: &tfbridge.DefaultInfo{
					EnvVars: []string{"AIRBYTE_PASSWORD"},
				},
				Secret:         tfbridge.True(),
				MarkAsOptional: tfbridge.True(),
			},
			"username": {
				Default: &tfbridge.DefaultInfo{
					EnvVars: []string{"AIRBYTE_USERNAME"},
				},
				MarkAsOptional: tfbridge.True(),
			},
			"bearer_auth": {
				Default: &tfbridge.DefaultInfo{
					EnvVars: []string{"AIRBYTE_BEARER_AUTH"},
				},
				Secret:         tfbridge.True(),
				MarkAsOptional: tfbridge.True(),
			},
		},
		Resources: map[string]*tfbridge.ResourceInfo{
			"airbyte_connection":                            {Tok: airbyteResource(airbyteMod, "Connection")},
			"airbyte_workspace":                             {Tok: airbyteResource(airbyteMod, "Workspace")},
			"airbyte_destination_snowflake":                 {Tok: airbyteResource(airbyteMod, "DestinationSnowflake")},
			"airbyte_source_salesforce":                     {Tok: airbyteResource(airbyteMod, "SourceSalesforce")},
			"airbyte_source_mixpanel":                       {Tok: airbyteResource(airbyteMod, "SourceMixpanel")},
			"airbyte_destination_aws_datalake":              {Tok: airbyteResource(airbyteMod, "DestinationAWSDatalake")},
			"airbyte_destination_azure_blob_storage":        {Tok: airbyteResource(airbyteMod, "DestinationAzureBlobStorage")},
			"airbyte_destination_bigquery":                  {Tok: airbyteResource(airbyteMod, "DestinationBigquery")},
			"airbyte_destination_bigquery_denormalized":     {Tok: airbyteResource(airbyteMod, "DestinationBigqueryDenormalized")},
			"airbyte_destination_clickhouse":                {Tok: airbyteResource(airbyteMod, "DestinationClickhouse")},
			"airbyte_destination_convex":                    {Tok: airbyteResource(airbyteMod, "DestinationConvex")},
			"airbyte_destination_cumulio":                   {Tok: airbyteResource(airbyteMod, "DestinationCumulio")},
			"airbyte_destination_databend":                  {Tok: airbyteResource(airbyteMod, "DestinationDatabend")},
			"airbyte_destination_databricks":                {Tok: airbyteResource(airbyteMod, "DestinationDatabricks")},
			"airbyte_destination_dev_null":                  {Tok: airbyteResource(airbyteMod, "DestinationDevNull")},
			"airbyte_destination_dynamodb":                  {Tok: airbyteResource(airbyteMod, "DestinationDynamodb")},
			"airbyte_destination_elasticsearch":             {Tok: airbyteResource(airbyteMod, "DestinationElasticsearch")},
			"airbyte_destination_firebolt":                  {Tok: airbyteResource(airbyteMod, "DestinationFirebolt")},
			"airbyte_destination_firestore":                 {Tok: airbyteResource(airbyteMod, "DestinationFirestore")},
			"airbyte_destination_gcs":                       {Tok: airbyteResource(airbyteMod, "DestinationGcs")},
			"airbyte_destination_google_sheets":             {Tok: airbyteResource(airbyteMod, "DestinationGoogleSheets")},
			"airbyte_destination_keen":                      {Tok: airbyteResource(airbyteMod, "DestinationKeen")},
			"airbyte_destination_kinesis":                   {Tok: airbyteResource(airbyteMod, "DestinationKinesis")},
			"airbyte_destination_langchain":                 {Tok: airbyteResource(airbyteMod, "DestinationLangchain")},
			"airbyte_destination_mongodb":                   {Tok: airbyteResource(airbyteMod, "DestinationMongodb")},
			"airbyte_destination_mssql":                     {Tok: airbyteResource(airbyteMod, "DestinationMSsql")},
			"airbyte_destination_mysql":                     {Tok: airbyteResource(airbyteMod, "DestinationMysql")},
			"airbyte_destination_oracle":                    {Tok: airbyteResource(airbyteMod, "DestinationOracle")},
			"airbyte_destination_postgres":                  {Tok: airbyteResource(airbyteMod, "DestinationPostgres")},
			"airbyte_destination_pubsub":                    {Tok: airbyteResource(airbyteMod, "DestinationPubsub")},
			"airbyte_destination_redis":                     {Tok: airbyteResource(airbyteMod, "DestinationRedis")},
			"airbyte_destination_redshift":                  {Tok: airbyteResource(airbyteMod, "DestinationRedshift")},
			"airbyte_destination_s3":                        {Tok: airbyteResource(airbyteMod, "DestinationS3")},
			"airbyte_destination_s3_glue":                   {Tok: airbyteResource(airbyteMod, "DestinationS3Glue")},
			"airbyte_destination_sftp_json":                 {Tok: airbyteResource(airbyteMod, "DestinationSftpJson")},
			"airbyte_destination_timeplus":                  {Tok: airbyteResource(airbyteMod, "DestinationTimeplus")},
			"airbyte_destination_typesense":                 {Tok: airbyteResource(airbyteMod, "DestinationTypesense")},
			"airbyte_destination_vertica":                   {Tok: airbyteResource(airbyteMod, "DestinationVertica")},
			"airbyte_destination_xata":                      {Tok: airbyteResource(airbyteMod, "DestinationXata")},
			"airbyte_source_aha":                            {Tok: airbyteResource(airbyteMod, "SourceAha")},
			"airbyte_source_aircall":                        {Tok: airbyteResource(airbyteMod, "SourceAircall")},
			"airbyte_source_airtable":                       {Tok: airbyteResource(airbyteMod, "SourceAirtable")},
			"airbyte_source_alloydb":                        {Tok: airbyteResource(airbyteMod, "SourceAlloydb")},
			"airbyte_source_amazon_ads":                     {Tok: airbyteResource(airbyteMod, "SourceAmazonAds")},
			"airbyte_source_amazon_seller_partner":          {Tok: airbyteResource(airbyteMod, "SourceAmazonSellerPartner")},
			"airbyte_source_amazon_sqs":                     {Tok: airbyteResource(airbyteMod, "SourceAmazonSqs")},
			"airbyte_source_amplitude":                      {Tok: airbyteResource(airbyteMod, "SourceAmplitude")},
			"airbyte_source_apify_dataset":                  {Tok: airbyteResource(airbyteMod, "SourceApifyDataset")},
			"airbyte_source_appfollow":                      {Tok: airbyteResource(airbyteMod, "SourceAppfollow")},
			"airbyte_source_asana":                          {Tok: airbyteResource(airbyteMod, "SourceAsana")},
			"airbyte_source_auth0":                          {Tok: airbyteResource(airbyteMod, "SourceAuth0")},
			"airbyte_source_aws_cloudtrail":                 {Tok: airbyteResource(airbyteMod, "SourceAwsCloudtrail")},
			"airbyte_source_azure_blob_storage":             {Tok: airbyteResource(airbyteMod, "SourceAzureBlobStorage")},
			"airbyte_source_azure_table":                    {Tok: airbyteResource(airbyteMod, "SourceAzureTable")},
			"airbyte_source_bamboo_hr":                      {Tok: airbyteResource(airbyteMod, "SourceBambooHr")},
			"airbyte_source_bigcommerce":                    {Tok: airbyteResource(airbyteMod, "SourceBigcommerce")},
			"airbyte_source_bigquery":                       {Tok: airbyteResource(airbyteMod, "SourceBigquery")},
			"airbyte_source_bing_ads":                       {Tok: airbyteResource(airbyteMod, "SourceBingAds")},
			"airbyte_source_braintree":                      {Tok: airbyteResource(airbyteMod, "SourceBraintree")},
			"airbyte_source_braze":                          {Tok: airbyteResource(airbyteMod, "SourceBraze")},
			"airbyte_source_chargebee":                      {Tok: airbyteResource(airbyteMod, "SourceChargebee")},
			"airbyte_source_chartmogul":                     {Tok: airbyteResource(airbyteMod, "SourceChartmogul")},
			"airbyte_source_clickhouse":                     {Tok: airbyteResource(airbyteMod, "SourceClickhouse")},
			"airbyte_source_clickup_api":                    {Tok: airbyteResource(airbyteMod, "SourceClickupApi")},
			"airbyte_source_clockify":                       {Tok: airbyteResource(airbyteMod, "SourceClockify")},
			"airbyte_source_close_com":                      {Tok: airbyteResource(airbyteMod, "SourceCloseCom")},
			"airbyte_source_coda":                           {Tok: airbyteResource(airbyteMod, "SourceCoda")},
			"airbyte_source_coin_api":                       {Tok: airbyteResource(airbyteMod, "SourceCoinApi")},
			"airbyte_source_coinmarketcap":                  {Tok: airbyteResource(airbyteMod, "SourceCoinmarketcap")},
			"airbyte_source_configcat":                      {Tok: airbyteResource(airbyteMod, "SourceConfigcat")},
			"airbyte_source_confluence":                     {Tok: airbyteResource(airbyteMod, "SourceConfluence")},
			"airbyte_source_convex":                         {Tok: airbyteResource(airbyteMod, "SourceConvex")},
			"airbyte_source_datadog":                        {Tok: airbyteResource(airbyteMod, "SourceDatadog")},
			"airbyte_source_datascope":                      {Tok: airbyteResource(airbyteMod, "SourceDatascope")},
			"airbyte_source_delighted":                      {Tok: airbyteResource(airbyteMod, "SourceDelighted")},
			"airbyte_source_dixa":                           {Tok: airbyteResource(airbyteMod, "SourceDixa")},
			"airbyte_source_dockerhub":                      {Tok: airbyteResource(airbyteMod, "SourceDockerhub")},
			"airbyte_source_dremio":                         {Tok: airbyteResource(airbyteMod, "SourceDremio")},
			"airbyte_source_dynamodb":                       {Tok: airbyteResource(airbyteMod, "SourceDynamodb")},
			"airbyte_source_e2e_test_cloud":                 {Tok: airbyteResource(airbyteMod, "SourceE2eTestCloud")},
			"airbyte_source_emailoctopus":                   {Tok: airbyteResource(airbyteMod, "SourceEmailoctopus")},
			"airbyte_source_exchange_rates":                 {Tok: airbyteResource(airbyteMod, "SourceExchangeRates")},
			"airbyte_source_facebook_marketing":             {Tok: airbyteResource(airbyteMod, "SourceFacebookMarketing")},
			"airbyte_source_facebook_pages":                 {Tok: airbyteResource(airbyteMod, "SourceFacebookPages")},
			"airbyte_source_faker":                          {Tok: airbyteResource(airbyteMod, "SourceFaker")},
			"airbyte_source_fauna":                          {Tok: airbyteResource(airbyteMod, "SourceFauna")},
			"airbyte_source_file_secure":                    {Tok: airbyteResource(airbyteMod, "SourceFileSecure")},
			"airbyte_source_firebolt":                       {Tok: airbyteResource(airbyteMod, "SourceFirebolt")},
			"airbyte_source_freshcaller":                    {Tok: airbyteResource(airbyteMod, "SourceFreshcaller")},
			"airbyte_source_freshdesk":                      {Tok: airbyteResource(airbyteMod, "SourceFreshdesk")},
			"airbyte_source_freshsales":                     {Tok: airbyteResource(airbyteMod, "SourceFreshsales")},
			"airbyte_source_gainsight_px":                   {Tok: airbyteResource(airbyteMod, "SourceGainsightPx")},
			"airbyte_source_gcs":                            {Tok: airbyteResource(airbyteMod, "SourceGcs")},
			"airbyte_source_getlago":                        {Tok: airbyteResource(airbyteMod, "SourceGetlago")},
			"airbyte_source_github":                         {Tok: airbyteResource(airbyteMod, "SourceGithub")},
			"airbyte_source_gitlab":                         {Tok: airbyteResource(airbyteMod, "SourceGitlab")},
			"airbyte_source_glassfrog":                      {Tok: airbyteResource(airbyteMod, "SourceGlassfrog")},
			"airbyte_source_gnews":                          {Tok: airbyteResource(airbyteMod, "SourceGnews")},
			"airbyte_source_google_ads":                     {Tok: airbyteResource(airbyteMod, "SourceGoogleAds")},
			"airbyte_source_google_analytics_data_api":      {Tok: airbyteResource(airbyteMod, "SourceGoogleAnalyticsDataApi")},
			"airbyte_source_google_analytics_v4":            {Tok: airbyteResource(airbyteMod, "SourceGoogleAnalyticsV4")},
			"airbyte_source_google_directory":               {Tok: airbyteResource(airbyteMod, "SourceGoogleDirectory")},
			"airbyte_source_google_pagespeed_insights":      {Tok: airbyteResource(airbyteMod, "SourceGooglePagespeedInsights")},
			"airbyte_source_google_search_console":          {Tok: airbyteResource(airbyteMod, "SourceGoogleSearchConsole")},
			"airbyte_source_google_sheets":                  {Tok: airbyteResource(airbyteMod, "SourceGoogleSheets")},
			"airbyte_source_google_webfonts":                {Tok: airbyteResource(airbyteMod, "SourceGoogleWebfonts")},
			"airbyte_source_google_workspace_admin_reports": {Tok: airbyteResource(airbyteMod, "SourceGoogleWorkspaceAdminReports")},
			"airbyte_source_greenhouse":                     {Tok: airbyteResource(airbyteMod, "SourceGreenhouse")},
			"airbyte_source_gridly":                         {Tok: airbyteResource(airbyteMod, "SourceGridly")},
			"airbyte_source_harvest":                        {Tok: airbyteResource(airbyteMod, "SourceHarvest")},
			"airbyte_source_hubplanner":                     {Tok: airbyteResource(airbyteMod, "SourceHubplanner")},
			"airbyte_source_hubspot":                        {Tok: airbyteResource(airbyteMod, "SourceHubspot")},
			"airbyte_source_insightly":                      {Tok: airbyteResource(airbyteMod, "SourceInsightly")},
			"airbyte_source_instagram":                      {Tok: airbyteResource(airbyteMod, "SourceInstagram")},
			"airbyte_source_instatus":                       {Tok: airbyteResource(airbyteMod, "SourceInstatus")},
			"airbyte_source_intercom":                       {Tok: airbyteResource(airbyteMod, "SourceIntercom")},
			"airbyte_source_ip2whois":                       {Tok: airbyteResource(airbyteMod, "SourceIp2whois")},
			"airbyte_source_iterable":                       {Tok: airbyteResource(airbyteMod, "SourceIterable")},
			"airbyte_source_jira":                           {Tok: airbyteResource(airbyteMod, "SourceJira")},
			"airbyte_source_k6_cloud":                       {Tok: airbyteResource(airbyteMod, "SourceK6Cloud")},
			"airbyte_source_klarna":                         {Tok: airbyteResource(airbyteMod, "SourceKlarna")},
			"airbyte_source_klaviyo":                        {Tok: airbyteResource(airbyteMod, "SourceKlaviyo")},
			"airbyte_source_kustomer_singer":                {Tok: airbyteResource(airbyteMod, "SourceKustomerSinger")},
			"airbyte_source_kyve":                           {Tok: airbyteResource(airbyteMod, "SourceKyve")},
			"airbyte_source_launchdarkly":                   {Tok: airbyteResource(airbyteMod, "SourceLaunchdarkly")},
			"airbyte_source_lemlist":                        {Tok: airbyteResource(airbyteMod, "SourceLemlist")},
			"airbyte_source_lever_hiring":                   {Tok: airbyteResource(airbyteMod, "SourceLeverHiring")},
			"airbyte_source_linkedin_ads":                   {Tok: airbyteResource(airbyteMod, "SourceLinkedinAds")},
			"airbyte_source_linkedin_pages":                 {Tok: airbyteResource(airbyteMod, "SourceLinkedinPages")},
			"airbyte_source_linnworks":                      {Tok: airbyteResource(airbyteMod, "SourceLinnworks")},
			"airbyte_source_lokalise":                       {Tok: airbyteResource(airbyteMod, "SourceLokalise")},
			"airbyte_source_mailchimp":                      {Tok: airbyteResource(airbyteMod, "SourceMailchimp")},
			"airbyte_source_mailgun":                        {Tok: airbyteResource(airbyteMod, "SourceMailgun")},
			"airbyte_source_mailjet_sms":                    {Tok: airbyteResource(airbyteMod, "SourceMailjetSms")},
			"airbyte_source_marketo":                        {Tok: airbyteResource(airbyteMod, "SourceMarketo")},
			"airbyte_source_metabase":                       {Tok: airbyteResource(airbyteMod, "SourceMetabase")},
			"airbyte_source_microsoft_teams":                {Tok: airbyteResource(airbyteMod, "SourceMicrosoftTeams")},
			"airbyte_source_monday":                         {Tok: airbyteResource(airbyteMod, "SourceMonday")},
			"airbyte_source_mongodb":                        {Tok: airbyteResource(airbyteMod, "SourceMongodb")},
			"airbyte_source_mongodb_internal_poc":           {Tok: airbyteResource(airbyteMod, "SourceMongodbInternalPoc")},
			"airbyte_source_mssql":                          {Tok: airbyteResource(airbyteMod, "SourceMssql")},
			"airbyte_source_my_hours":                       {Tok: airbyteResource(airbyteMod, "SourceMyHours")},
			"airbyte_source_mysql":                          {Tok: airbyteResource(airbyteMod, "SourceMysql")},
			"airbyte_source_netsuite":                       {Tok: airbyteResource(airbyteMod, "SourceNetsuite")},
			"airbyte_source_notion":                         {Tok: airbyteResource(airbyteMod, "SourceNotion")},
			"airbyte_source_nytimes":                        {Tok: airbyteResource(airbyteMod, "SourceNytimes")},
			"airbyte_source_okta":                           {Tok: airbyteResource(airbyteMod, "SourceOkta")},
			"airbyte_source_omnisend":                       {Tok: airbyteResource(airbyteMod, "SourceOmnisend")},
			"airbyte_source_onesignal":                      {Tok: airbyteResource(airbyteMod, "SourceOnesignal")},
			"airbyte_source_openweather":                    {Tok: airbyteResource(airbyteMod, "SourceOpenweather")},
			"airbyte_source_oracle":                         {Tok: airbyteResource(airbyteMod, "SourceOracle")},
			"airbyte_source_orb":                            {Tok: airbyteResource(airbyteMod, "SourceOrb")},
			"airbyte_source_orbit":                          {Tok: airbyteResource(airbyteMod, "SourceOrbit")},
			"airbyte_source_outbrain_amplify":               {Tok: airbyteResource(airbyteMod, "SourceOutbrainAmplify")},
			"airbyte_source_outreach":                       {Tok: airbyteResource(airbyteMod, "SourceOutreach")},
			"airbyte_source_paypal_transaction":             {Tok: airbyteResource(airbyteMod, "SourcePaypalTransaction")},
			"airbyte_source_paystack":                       {Tok: airbyteResource(airbyteMod, "SourcePaystack")},
			"airbyte_source_pendo":                          {Tok: airbyteResource(airbyteMod, "SourcePendo")},
			"airbyte_source_persistiq":                      {Tok: airbyteResource(airbyteMod, "SourcePersistiq")},
			"airbyte_source_pexels_api":                     {Tok: airbyteResource(airbyteMod, "SourcePexelsApi")},
			"airbyte_source_pinterest":                      {Tok: airbyteResource(airbyteMod, "SourcePinterest")},
			"airbyte_source_pipedrive":                      {Tok: airbyteResource(airbyteMod, "SourcePipedrive")},
			"airbyte_source_pocket":                         {Tok: airbyteResource(airbyteMod, "SourcePocket")},
			"airbyte_source_pokeapi":                        {Tok: airbyteResource(airbyteMod, "SourcePokeapi")},
			"airbyte_source_polygon_stock_api":              {Tok: airbyteResource(airbyteMod, "SourcePolygonStockApi")},
			"airbyte_source_postgres":                       {Tok: airbyteResource(airbyteMod, "SourcePostgres")},
			"airbyte_source_posthog":                        {Tok: airbyteResource(airbyteMod, "SourcePosthog")},
			"airbyte_source_postmarkapp":                    {Tok: airbyteResource(airbyteMod, "SourcePostmarkapp")},
			"airbyte_source_prestashop":                     {Tok: airbyteResource(airbyteMod, "SourcePrestashop")},
			"airbyte_source_public_apis":                    {Tok: airbyteResource(airbyteMod, "SourcePublicApis")},
			"airbyte_source_punk_api":                       {Tok: airbyteResource(airbyteMod, "SourcePunkApi")},
			"airbyte_source_pypi":                           {Tok: airbyteResource(airbyteMod, "SourcePypi")},
			"airbyte_source_qualaroo":                       {Tok: airbyteResource(airbyteMod, "SourceQualaroo")},
			"airbyte_source_quickbooks":                     {Tok: airbyteResource(airbyteMod, "SourceQuickbooks")},
			"airbyte_source_railz":                          {Tok: airbyteResource(airbyteMod, "SourceRailz")},
			"airbyte_source_recharge":                       {Tok: airbyteResource(airbyteMod, "SourceRecharge")},
			"airbyte_source_recreation":                     {Tok: airbyteResource(airbyteMod, "SourceRecreation")},
			"airbyte_source_recruitee":                      {Tok: airbyteResource(airbyteMod, "SourceRecruitee")},
			"airbyte_source_recurly":                        {Tok: airbyteResource(airbyteMod, "SourceRecurly")},
			"airbyte_source_redshift":                       {Tok: airbyteResource(airbyteMod, "SourceRedshift")},
			"airbyte_source_retently":                       {Tok: airbyteResource(airbyteMod, "SourceRetently")},
			"airbyte_source_rki_covid":                      {Tok: airbyteResource(airbyteMod, "SourceRkiCovid")},
			"airbyte_source_rss":                            {Tok: airbyteResource(airbyteMod, "SourceRss")},
			"airbyte_source_s3":                             {Tok: airbyteResource(airbyteMod, "SourceS3")},
			"airbyte_source_salesloft":                      {Tok: airbyteResource(airbyteMod, "SourceSalesloft")},
			"airbyte_source_sap_fieldglass":                 {Tok: airbyteResource(airbyteMod, "SourceSapFieldglass")},
			"airbyte_source_secoda":                         {Tok: airbyteResource(airbyteMod, "SourceSecoda")},
			"airbyte_source_sendgrid":                       {Tok: airbyteResource(airbyteMod, "SourceSendgrid")},
			"airbyte_source_sendinblue":                     {Tok: airbyteResource(airbyteMod, "SourceSendinblue")},
			"airbyte_source_senseforce":                     {Tok: airbyteResource(airbyteMod, "SourceSenseforce")},
			"airbyte_source_sentry":                         {Tok: airbyteResource(airbyteMod, "SourceSentry")},
			"airbyte_source_sftp":                           {Tok: airbyteResource(airbyteMod, "SourceSftp")},
			"airbyte_source_sftp_bulk":                      {Tok: airbyteResource(airbyteMod, "SourceSftpBulk")},
			"airbyte_source_shopify":                        {Tok: airbyteResource(airbyteMod, "SourceShopify")},
			"airbyte_source_shortio":                        {Tok: airbyteResource(airbyteMod, "SourceShortio")},
			"airbyte_source_slack":                          {Tok: airbyteResource(airbyteMod, "SourceSlack")},
			"airbyte_source_smaily":                         {Tok: airbyteResource(airbyteMod, "SourceSmaily")},
			"airbyte_source_smartengage":                    {Tok: airbyteResource(airbyteMod, "SourceSmartengage")},
			"airbyte_source_smartsheets":                    {Tok: airbyteResource(airbyteMod, "SourceSmartsheets")},
			"airbyte_source_snapchat_marketing":             {Tok: airbyteResource(airbyteMod, "SourceSnapchatMarketing")},
			"airbyte_source_snowflake":                      {Tok: airbyteResource(airbyteMod, "SourceSnowflake")},
			"airbyte_source_sonar_cloud":                    {Tok: airbyteResource(airbyteMod, "SourceSonarCloud")},
			"airbyte_source_spacex_api":                     {Tok: airbyteResource(airbyteMod, "SourceSpaceXApi")},
			"airbyte_source_square":                         {Tok: airbyteResource(airbyteMod, "SourceSquare")},
			"airbyte_source_strava":                         {Tok: airbyteResource(airbyteMod, "SourceStrava")},
			"airbyte_source_stripe":                         {Tok: airbyteResource(airbyteMod, "SourceStripe")},
			"airbyte_source_survey_sparrow":                 {Tok: airbyteResource(airbyteMod, "SourceSurveySparrow")},
			"airbyte_source_surveymonkey":                   {Tok: airbyteResource(airbyteMod, "SourceSurveymonkey")},
			"airbyte_source_tempo":                          {Tok: airbyteResource(airbyteMod, "SourceTempo")},
			"airbyte_source_the_guardian_api":               {Tok: airbyteResource(airbyteMod, "SourceTheGuardianApi")},
			"airbyte_source_tiktok_marketing":               {Tok: airbyteResource(airbyteMod, "SourceTiktokMarketing")},
			"airbyte_source_todoist":                        {Tok: airbyteResource(airbyteMod, "SourceTodoist")},
			"airbyte_source_trello":                         {Tok: airbyteResource(airbyteMod, "SourceTrello")},
			"airbyte_source_trustpilot":                     {Tok: airbyteResource(airbyteMod, "SourceTrustpilot")},
			"airbyte_source_tvmaze_schedule":                {Tok: airbyteResource(airbyteMod, "SourceTvmazeSchedule")},
			"airbyte_source_twilio":                         {Tok: airbyteResource(airbyteMod, "SourceTwilio")},
			"airbyte_source_twilio_taskrouter":              {Tok: airbyteResource(airbyteMod, "SourceTwilioTaskrouter")},
			"airbyte_source_twitter":                        {Tok: airbyteResource(airbyteMod, "SourceTwitter")},
			"airbyte_source_typeform":                       {Tok: airbyteResource(airbyteMod, "SourceTypeform")},
			"airbyte_source_us_census":                      {Tok: airbyteResource(airbyteMod, "SourceUsCensus")},
			"airbyte_source_vantage":                        {Tok: airbyteResource(airbyteMod, "SourceVantage")},
			"airbyte_source_webflow":                        {Tok: airbyteResource(airbyteMod, "SourceWebflow")},
			"airbyte_source_whisky_hunter":                  {Tok: airbyteResource(airbyteMod, "SourceWhiskyHunter")},
			"airbyte_source_wikipedia_pageviews":            {Tok: airbyteResource(airbyteMod, "SourceWikipediaPageviews")},
			"airbyte_source_woocommerce":                    {Tok: airbyteResource(airbyteMod, "SourceWoocommerce")},
			"airbyte_source_xero":                           {Tok: airbyteResource(airbyteMod, "SourceXero")},
			"airbyte_source_xkcd":                           {Tok: airbyteResource(airbyteMod, "SourceXkcd")},
			"airbyte_source_yandex_metrica":                 {Tok: airbyteResource(airbyteMod, "SourceYandexMetrica")},
			"airbyte_source_yotpo":                          {Tok: airbyteResource(airbyteMod, "SourceYotpo")},
			"airbyte_source_younium":                        {Tok: airbyteResource(airbyteMod, "SourceYounium")},
			"airbyte_source_youtube_analytics":              {Tok: airbyteResource(airbyteMod, "SourceYoutubeAnalytics")},
			"airbyte_source_zendesk_chat":                   {Tok: airbyteResource(airbyteMod, "SourceZendeskChat")},
			"airbyte_source_zendesk_sunshine":               {Tok: airbyteResource(airbyteMod, "SourceZendeskSunshine")},
			"airbyte_source_zendesk_support":                {Tok: airbyteResource(airbyteMod, "SourceZendeskSupport")},
			"airbyte_source_zendesk_talk":                   {Tok: airbyteResource(airbyteMod, "SourceZendeskTalk")},
			"airbyte_source_zenloop":                        {Tok: airbyteResource(airbyteMod, "SourceZenloop")},
			"airbyte_source_zoho_crm":                       {Tok: airbyteResource(airbyteMod, "SourceZohoCrm")},
			"airbyte_source_zoom":                           {Tok: airbyteResource(airbyteMod, "SourceZoom")},
			"airbyte_source_zuora":                          {Tok: airbyteResource(airbyteMod, "SourceZuora")},
		},
		DataSources: map[string]*tfbridge.DataSourceInfo{
			"airbyte_connection":                            {Tok: airbyteDataSource(airbyteMod, "getConnection")},
			"airbyte_workspace":                             {Tok: airbyteDataSource(airbyteMod, "getWorkspace")},
			"airbyte_destination_snowflake":                 {Tok: airbyteDataSource(airbyteMod, "getDestinationSnowflake")},
			"airbyte_source_salesforce":                     {Tok: airbyteDataSource(airbyteMod, "getSourceSalesforce")},
			"airbyte_source_mixpanel":                       {Tok: airbyteDataSource(airbyteMod, "getSourceMixpanel")},
			"airbyte_destination_aws_datalake":              {Tok: airbyteDataSource(airbyteMod, "getDestinationAWSDatalake")},
			"airbyte_destination_azure_blob_storage":        {Tok: airbyteDataSource(airbyteMod, "getDestinationAzureBlobStorage")},
			"airbyte_destination_bigquery":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationBigquery")},
			"airbyte_destination_bigquery_denormalized":     {Tok: airbyteDataSource(airbyteMod, "getDestinationBigqueryDenormalized")},
			"airbyte_destination_clickhouse":                {Tok: airbyteDataSource(airbyteMod, "getDestinationClickhouse")},
			"airbyte_destination_convex":                    {Tok: airbyteDataSource(airbyteMod, "getDestinationConvex")},
			"airbyte_destination_cumulio":                   {Tok: airbyteDataSource(airbyteMod, "getDestinationCumulio")},
			"airbyte_destination_databend":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationDatabend")},
			"airbyte_destination_databricks":                {Tok: airbyteDataSource(airbyteMod, "getDestinationDatabricks")},
			"airbyte_destination_dev_null":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationDevNull")},
			"airbyte_destination_dynamodb":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationDynamodb")},
			"airbyte_destination_elasticsearch":             {Tok: airbyteDataSource(airbyteMod, "getDestinationElasticsearch")},
			"airbyte_destination_firebolt":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationFirebolt")},
			"airbyte_destination_firestore":                 {Tok: airbyteDataSource(airbyteMod, "getDestinationFirestore")},
			"airbyte_destination_gcs":                       {Tok: airbyteDataSource(airbyteMod, "getDestinationGcs")},
			"airbyte_destination_google_sheets":             {Tok: airbyteDataSource(airbyteMod, "getDestinationGoogleSheets")},
			"airbyte_destination_keen":                      {Tok: airbyteDataSource(airbyteMod, "getDestinationKeen")},
			"airbyte_destination_kinesis":                   {Tok: airbyteDataSource(airbyteMod, "getDestinationKinesis")},
			"airbyte_destination_langchain":                 {Tok: airbyteDataSource(airbyteMod, "getDestinationLangchain")},
			"airbyte_destination_mongodb":                   {Tok: airbyteDataSource(airbyteMod, "getDestinationMongodb")},
			"airbyte_destination_mssql":                     {Tok: airbyteDataSource(airbyteMod, "getDestinationMSsql")},
			"airbyte_destination_mysql":                     {Tok: airbyteDataSource(airbyteMod, "getDestinationMysql")},
			"airbyte_destination_oracle":                    {Tok: airbyteDataSource(airbyteMod, "getDestinationOracle")},
			"airbyte_destination_postgres":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationPostgres")},
			"airbyte_destination_pubsub":                    {Tok: airbyteDataSource(airbyteMod, "getDestinationPubsub")},
			"airbyte_destination_redis":                     {Tok: airbyteDataSource(airbyteMod, "getDestinationRedis")},
			"airbyte_destination_redshift":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationRedshift")},
			"airbyte_destination_s3":                        {Tok: airbyteDataSource(airbyteMod, "getDestinationS3")},
			"airbyte_destination_s3_glue":                   {Tok: airbyteDataSource(airbyteMod, "getDestinationS3Glue")},
			"airbyte_destination_sftp_json":                 {Tok: airbyteDataSource(airbyteMod, "getDestinationSftpJson")},
			"airbyte_destination_timeplus":                  {Tok: airbyteDataSource(airbyteMod, "getDestinationTimeplus")},
			"airbyte_destination_typesense":                 {Tok: airbyteDataSource(airbyteMod, "getDestinationTypesense")},
			"airbyte_destination_vertica":                   {Tok: airbyteDataSource(airbyteMod, "getDestinationVertica")},
			"airbyte_destination_xata":                      {Tok: airbyteDataSource(airbyteMod, "getDestinationXata")},
			"airbyte_source_aha":                            {Tok: airbyteDataSource(airbyteMod, "getSourceAha")},
			"airbyte_source_aircall":                        {Tok: airbyteDataSource(airbyteMod, "getSourceAircall")},
			"airbyte_source_airtable":                       {Tok: airbyteDataSource(airbyteMod, "getSourceAirtable")},
			"airbyte_source_alloydb":                        {Tok: airbyteDataSource(airbyteMod, "getSourceAlloydb")},
			"airbyte_source_amazon_ads":                     {Tok: airbyteDataSource(airbyteMod, "getSourceAmazonAds")},
			"airbyte_source_amazon_seller_partner":          {Tok: airbyteDataSource(airbyteMod, "getSourceAmazonSellerPartner")},
			"airbyte_source_amazon_sqs":                     {Tok: airbyteDataSource(airbyteMod, "getSourceAmazonSqs")},
			"airbyte_source_amplitude":                      {Tok: airbyteDataSource(airbyteMod, "getSourceAmplitude")},
			"airbyte_source_apify_dataset":                  {Tok: airbyteDataSource(airbyteMod, "getSourceApifyDataset")},
			"airbyte_source_appfollow":                      {Tok: airbyteDataSource(airbyteMod, "getSourceAppfollow")},
			"airbyte_source_asana":                          {Tok: airbyteDataSource(airbyteMod, "getSourceAsana")},
			"airbyte_source_auth0":                          {Tok: airbyteDataSource(airbyteMod, "getSourceAuth0")},
			"airbyte_source_aws_cloudtrail":                 {Tok: airbyteDataSource(airbyteMod, "getSourceAwsCloudtrail")},
			"airbyte_source_azure_blob_storage":             {Tok: airbyteDataSource(airbyteMod, "getSourceAzureBlobStorage")},
			"airbyte_source_azure_table":                    {Tok: airbyteDataSource(airbyteMod, "getSourceAzureTable")},
			"airbyte_source_bamboo_hr":                      {Tok: airbyteDataSource(airbyteMod, "getSourceBambooHr")},
			"airbyte_source_bigcommerce":                    {Tok: airbyteDataSource(airbyteMod, "getSourceBigcommerce")},
			"airbyte_source_bigquery":                       {Tok: airbyteDataSource(airbyteMod, "getSourceBigquery")},
			"airbyte_source_bing_ads":                       {Tok: airbyteDataSource(airbyteMod, "getSourceBingAds")},
			"airbyte_source_braintree":                      {Tok: airbyteDataSource(airbyteMod, "getSourceBraintree")},
			"airbyte_source_braze":                          {Tok: airbyteDataSource(airbyteMod, "getSourceBraze")},
			"airbyte_source_chargebee":                      {Tok: airbyteDataSource(airbyteMod, "getSourceChargebee")},
			"airbyte_source_chartmogul":                     {Tok: airbyteDataSource(airbyteMod, "getSourceChartmogul")},
			"airbyte_source_clickhouse":                     {Tok: airbyteDataSource(airbyteMod, "getSourceClickhouse")},
			"airbyte_source_clickup_api":                    {Tok: airbyteDataSource(airbyteMod, "getSourceClickupApi")},
			"airbyte_source_clockify":                       {Tok: airbyteDataSource(airbyteMod, "getSourceClockify")},
			"airbyte_source_close_com":                      {Tok: airbyteDataSource(airbyteMod, "getSourceCloseCom")},
			"airbyte_source_coda":                           {Tok: airbyteDataSource(airbyteMod, "getSourceCoda")},
			"airbyte_source_coin_api":                       {Tok: airbyteDataSource(airbyteMod, "getSourceCoinApi")},
			"airbyte_source_coinmarketcap":                  {Tok: airbyteDataSource(airbyteMod, "getSourceCoinmarketcap")},
			"airbyte_source_configcat":                      {Tok: airbyteDataSource(airbyteMod, "getSourceConfigcat")},
			"airbyte_source_confluence":                     {Tok: airbyteDataSource(airbyteMod, "getSourceConfluence")},
			"airbyte_source_convex":                         {Tok: airbyteDataSource(airbyteMod, "getSourceConvex")},
			"airbyte_source_datadog":                        {Tok: airbyteDataSource(airbyteMod, "getSourceDatadog")},
			"airbyte_source_datascope":                      {Tok: airbyteDataSource(airbyteMod, "getSourceDatascope")},
			"airbyte_source_delighted":                      {Tok: airbyteDataSource(airbyteMod, "getSourceDelighted")},
			"airbyte_source_dixa":                           {Tok: airbyteDataSource(airbyteMod, "getSourceDixa")},
			"airbyte_source_dockerhub":                      {Tok: airbyteDataSource(airbyteMod, "getSourceDockerhub")},
			"airbyte_source_dremio":                         {Tok: airbyteDataSource(airbyteMod, "getSourceDremio")},
			"airbyte_source_dynamodb":                       {Tok: airbyteDataSource(airbyteMod, "getSourceDynamodb")},
			"airbyte_source_e2e_test_cloud":                 {Tok: airbyteDataSource(airbyteMod, "getSourceE2eTestCloud")},
			"airbyte_source_emailoctopus":                   {Tok: airbyteDataSource(airbyteMod, "getSourceEmailoctopus")},
			"airbyte_source_exchange_rates":                 {Tok: airbyteDataSource(airbyteMod, "getSourceExchangeRates")},
			"airbyte_source_facebook_marketing":             {Tok: airbyteDataSource(airbyteMod, "getSourceFacebookMarketing")},
			"airbyte_source_facebook_pages":                 {Tok: airbyteDataSource(airbyteMod, "getSourceFacebookPages")},
			"airbyte_source_faker":                          {Tok: airbyteDataSource(airbyteMod, "getSourceFaker")},
			"airbyte_source_fauna":                          {Tok: airbyteDataSource(airbyteMod, "getSourceFauna")},
			"airbyte_source_file_secure":                    {Tok: airbyteDataSource(airbyteMod, "getSourceFileSecure")},
			"airbyte_source_firebolt":                       {Tok: airbyteDataSource(airbyteMod, "getSourceFirebolt")},
			"airbyte_source_freshcaller":                    {Tok: airbyteDataSource(airbyteMod, "getSourceFreshcaller")},
			"airbyte_source_freshdesk":                      {Tok: airbyteDataSource(airbyteMod, "getSourceFreshdesk")},
			"airbyte_source_freshsales":                     {Tok: airbyteDataSource(airbyteMod, "getSourceFreshsales")},
			"airbyte_source_gainsight_px":                   {Tok: airbyteDataSource(airbyteMod, "getSourceGainsightPx")},
			"airbyte_source_gcs":                            {Tok: airbyteDataSource(airbyteMod, "getSourceGcs")},
			"airbyte_source_getlago":                        {Tok: airbyteDataSource(airbyteMod, "getSourceGetlago")},
			"airbyte_source_github":                         {Tok: airbyteDataSource(airbyteMod, "getSourceGithub")},
			"airbyte_source_gitlab":                         {Tok: airbyteDataSource(airbyteMod, "getSourceGitlab")},
			"airbyte_source_glassfrog":                      {Tok: airbyteDataSource(airbyteMod, "getSourceGlassfrog")},
			"airbyte_source_gnews":                          {Tok: airbyteDataSource(airbyteMod, "getSourceGnews")},
			"airbyte_source_google_ads":                     {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleAds")},
			"airbyte_source_google_analytics_data_api":      {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleAnalyticsDataApi")},
			"airbyte_source_google_analytics_v4":            {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleAnalyticsV4")},
			"airbyte_source_google_directory":               {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleDirectory")},
			"airbyte_source_google_pagespeed_insights":      {Tok: airbyteDataSource(airbyteMod, "getSourceGooglePagespeedInsights")},
			"airbyte_source_google_search_console":          {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleSearchConsole")},
			"airbyte_source_google_sheets":                  {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleSheets")},
			"airbyte_source_google_webfonts":                {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleWebfonts")},
			"airbyte_source_google_workspace_admin_reports": {Tok: airbyteDataSource(airbyteMod, "getSourceGoogleWorkspaceAdminReports")},
			"airbyte_source_greenhouse":                     {Tok: airbyteDataSource(airbyteMod, "getSourceGreenhouse")},
			"airbyte_source_gridly":                         {Tok: airbyteDataSource(airbyteMod, "getSourceGridly")},
			"airbyte_source_harvest":                        {Tok: airbyteDataSource(airbyteMod, "getSourceHarvest")},
			"airbyte_source_hubplanner":                     {Tok: airbyteDataSource(airbyteMod, "getSourceHubplanner")},
			"airbyte_source_hubspot":                        {Tok: airbyteDataSource(airbyteMod, "getSourceHubspot")},
			"airbyte_source_insightly":                      {Tok: airbyteDataSource(airbyteMod, "getSourceInsightly")},
			"airbyte_source_instagram":                      {Tok: airbyteDataSource(airbyteMod, "getSourceInstagram")},
			"airbyte_source_instatus":                       {Tok: airbyteDataSource(airbyteMod, "getSourceInstatus")},
			"airbyte_source_intercom":                       {Tok: airbyteDataSource(airbyteMod, "getSourceIntercom")},
			"airbyte_source_ip2whois":                       {Tok: airbyteDataSource(airbyteMod, "getSourceIp2whois")},
			"airbyte_source_iterable":                       {Tok: airbyteDataSource(airbyteMod, "getSourceIterable")},
			"airbyte_source_jira":                           {Tok: airbyteDataSource(airbyteMod, "getSourceJira")},
			"airbyte_source_k6_cloud":                       {Tok: airbyteDataSource(airbyteMod, "getSourceK6Cloud")},
			"airbyte_source_klarna":                         {Tok: airbyteDataSource(airbyteMod, "getSourceKlarna")},
			"airbyte_source_klaviyo":                        {Tok: airbyteDataSource(airbyteMod, "getSourceKlaviyo")},
			"airbyte_source_kustomer_singer":                {Tok: airbyteDataSource(airbyteMod, "getSourceKustomerSinger")},
			"airbyte_source_kyve":                           {Tok: airbyteDataSource(airbyteMod, "getSourceKyve")},
			"airbyte_source_launchdarkly":                   {Tok: airbyteDataSource(airbyteMod, "getSourceLaunchdarkly")},
			"airbyte_source_lemlist":                        {Tok: airbyteDataSource(airbyteMod, "getSourceLemlist")},
			"airbyte_source_lever_hiring":                   {Tok: airbyteDataSource(airbyteMod, "getSourceLeverHiring")},
			"airbyte_source_linkedin_ads":                   {Tok: airbyteDataSource(airbyteMod, "getSourceLinkedinAds")},
			"airbyte_source_linkedin_pages":                 {Tok: airbyteDataSource(airbyteMod, "getSourceLinkedinPages")},
			"airbyte_source_linnworks":                      {Tok: airbyteDataSource(airbyteMod, "getSourceLinnworks")},
			"airbyte_source_lokalise":                       {Tok: airbyteDataSource(airbyteMod, "getSourceLokalise")},
			"airbyte_source_mailchimp":                      {Tok: airbyteDataSource(airbyteMod, "getSourceMailchimp")},
			"airbyte_source_mailgun":                        {Tok: airbyteDataSource(airbyteMod, "getSourceMailgun")},
			"airbyte_source_mailjet_sms":                    {Tok: airbyteDataSource(airbyteMod, "getSourceMailjetSms")},
			"airbyte_source_marketo":                        {Tok: airbyteDataSource(airbyteMod, "getSourceMarketo")},
			"airbyte_source_metabase":                       {Tok: airbyteDataSource(airbyteMod, "getSourceMetabase")},
			"airbyte_source_microsoft_teams":                {Tok: airbyteDataSource(airbyteMod, "getSourceMicrosoftTeams")},
			"airbyte_source_monday":                         {Tok: airbyteDataSource(airbyteMod, "getSourceMonday")},
			"airbyte_source_mongodb":                        {Tok: airbyteDataSource(airbyteMod, "getSourceMongodb")},
			"airbyte_source_mongodb_internal_poc":           {Tok: airbyteDataSource(airbyteMod, "getSourceMongodbInternalPoc")},
			"airbyte_source_mssql":                          {Tok: airbyteDataSource(airbyteMod, "getSourceMssql")},
			"airbyte_source_my_hours":                       {Tok: airbyteDataSource(airbyteMod, "getSourceMyHours")},
			"airbyte_source_mysql":                          {Tok: airbyteDataSource(airbyteMod, "getSourceMysql")},
			"airbyte_source_netsuite":                       {Tok: airbyteDataSource(airbyteMod, "getSourceNetsuite")},
			"airbyte_source_notion":                         {Tok: airbyteDataSource(airbyteMod, "getSourceNotion")},
			"airbyte_source_nytimes":                        {Tok: airbyteDataSource(airbyteMod, "getSourceNytimes")},
			"airbyte_source_okta":                           {Tok: airbyteDataSource(airbyteMod, "getSourceOkta")},
			"airbyte_source_omnisend":                       {Tok: airbyteDataSource(airbyteMod, "getSourceOmnisend")},
			"airbyte_source_onesignal":                      {Tok: airbyteDataSource(airbyteMod, "getSourceOnesignal")},
			"airbyte_source_openweather":                    {Tok: airbyteDataSource(airbyteMod, "getSourceOpenweather")},
			"airbyte_source_oracle":                         {Tok: airbyteDataSource(airbyteMod, "getSourceOracle")},
			"airbyte_source_orb":                            {Tok: airbyteDataSource(airbyteMod, "getSourceOrb")},
			"airbyte_source_orbit":                          {Tok: airbyteDataSource(airbyteMod, "getSourceOrbit")},
			"airbyte_source_outbrain_amplify":               {Tok: airbyteDataSource(airbyteMod, "getSourceOutbrainAmplify")},
			"airbyte_source_outreach":                       {Tok: airbyteDataSource(airbyteMod, "getSourceOutreach")},
			"airbyte_source_paypal_transaction":             {Tok: airbyteDataSource(airbyteMod, "getSourcePaypalTransaction")},
			"airbyte_source_paystack":                       {Tok: airbyteDataSource(airbyteMod, "getSourcePaystack")},
			"airbyte_source_pendo":                          {Tok: airbyteDataSource(airbyteMod, "getSourcePendo")},
			"airbyte_source_persistiq":                      {Tok: airbyteDataSource(airbyteMod, "getSourcePersistiq")},
			"airbyte_source_pexels_api":                     {Tok: airbyteDataSource(airbyteMod, "getSourcePexelsApi")},
			"airbyte_source_pinterest":                      {Tok: airbyteDataSource(airbyteMod, "getSourcePinterest")},
			"airbyte_source_pipedrive":                      {Tok: airbyteDataSource(airbyteMod, "getSourcePipedrive")},
			"airbyte_source_pocket":                         {Tok: airbyteDataSource(airbyteMod, "getSourcePocket")},
			"airbyte_source_pokeapi":                        {Tok: airbyteDataSource(airbyteMod, "getSourcePokeapi")},
			"airbyte_source_polygon_stock_api":              {Tok: airbyteDataSource(airbyteMod, "getSourcePolygonStockApi")},
			"airbyte_source_postgres":                       {Tok: airbyteDataSource(airbyteMod, "getSourcePostgres")},
			"airbyte_source_posthog":                        {Tok: airbyteDataSource(airbyteMod, "getSourcePosthog")},
			"airbyte_source_postmarkapp":                    {Tok: airbyteDataSource(airbyteMod, "getSourcePostmarkapp")},
			"airbyte_source_prestashop":                     {Tok: airbyteDataSource(airbyteMod, "getSourcePrestashop")},
			"airbyte_source_public_apis":                    {Tok: airbyteDataSource(airbyteMod, "getSourcePublicApis")},
			"airbyte_source_punk_api":                       {Tok: airbyteDataSource(airbyteMod, "getSourcePunkApi")},
			"airbyte_source_pypi":                           {Tok: airbyteDataSource(airbyteMod, "getSourcePypi")},
			"airbyte_source_qualaroo":                       {Tok: airbyteDataSource(airbyteMod, "getSourceQualaroo")},
			"airbyte_source_quickbooks":                     {Tok: airbyteDataSource(airbyteMod, "getSourceQuickbooks")},
			"airbyte_source_railz":                          {Tok: airbyteDataSource(airbyteMod, "getSourceRailz")},
			"airbyte_source_recharge":                       {Tok: airbyteDataSource(airbyteMod, "getSourceRecharge")},
			"airbyte_source_recreation":                     {Tok: airbyteDataSource(airbyteMod, "getSourceRecreation")},
			"airbyte_source_recruitee":                      {Tok: airbyteDataSource(airbyteMod, "getSourceRecruitee")},
			"airbyte_source_recurly":                        {Tok: airbyteDataSource(airbyteMod, "getSourceRecurly")},
			"airbyte_source_redshift":                       {Tok: airbyteDataSource(airbyteMod, "getSourceRedshift")},
			"airbyte_source_retently":                       {Tok: airbyteDataSource(airbyteMod, "getSourceRetently")},
			"airbyte_source_rki_covid":                      {Tok: airbyteDataSource(airbyteMod, "getSourceRkiCovid")},
			"airbyte_source_rss":                            {Tok: airbyteDataSource(airbyteMod, "getSourceRss")},
			"airbyte_source_s3":                             {Tok: airbyteDataSource(airbyteMod, "getSourceS3")},
			"airbyte_source_salesloft":                      {Tok: airbyteDataSource(airbyteMod, "getSourceSalesloft")},
			"airbyte_source_sap_fieldglass":                 {Tok: airbyteDataSource(airbyteMod, "getSourceSapFieldglass")},
			"airbyte_source_secoda":                         {Tok: airbyteDataSource(airbyteMod, "getSourceSecoda")},
			"airbyte_source_sendgrid":                       {Tok: airbyteDataSource(airbyteMod, "getSourceSendgrid")},
			"airbyte_source_sendinblue":                     {Tok: airbyteDataSource(airbyteMod, "getSourceSendinblue")},
			"airbyte_source_senseforce":                     {Tok: airbyteDataSource(airbyteMod, "getSourceSenseforce")},
			"airbyte_source_sentry":                         {Tok: airbyteDataSource(airbyteMod, "getSourceSentry")},
			"airbyte_source_sftp":                           {Tok: airbyteDataSource(airbyteMod, "getSourceSftp")},
			"airbyte_source_sftp_bulk":                      {Tok: airbyteDataSource(airbyteMod, "getSourceSftpBulk")},
			"airbyte_source_shopify":                        {Tok: airbyteDataSource(airbyteMod, "getSourceShopify")},
			"airbyte_source_shortio":                        {Tok: airbyteDataSource(airbyteMod, "getSourceShortio")},
			"airbyte_source_slack":                          {Tok: airbyteDataSource(airbyteMod, "getSourceSlack")},
			"airbyte_source_smaily":                         {Tok: airbyteDataSource(airbyteMod, "getSourceSmaily")},
			"airbyte_source_smartengage":                    {Tok: airbyteDataSource(airbyteMod, "getSourceSmartengage")},
			"airbyte_source_smartsheets":                    {Tok: airbyteDataSource(airbyteMod, "getSourceSmartsheets")},
			"airbyte_source_snapchat_marketing":             {Tok: airbyteDataSource(airbyteMod, "getSourceSnapchatMarketing")},
			"airbyte_source_snowflake":                      {Tok: airbyteDataSource(airbyteMod, "getSourceSnowflake")},
			"airbyte_source_sonar_cloud":                    {Tok: airbyteDataSource(airbyteMod, "getSourceSonarCloud")},
			"airbyte_source_spacex_api":                     {Tok: airbyteDataSource(airbyteMod, "getSourceSpaceXApi")},
			"airbyte_source_square":                         {Tok: airbyteDataSource(airbyteMod, "getSourceSquare")},
			"airbyte_source_strava":                         {Tok: airbyteDataSource(airbyteMod, "getSourceStrava")},
			"airbyte_source_stripe":                         {Tok: airbyteDataSource(airbyteMod, "getSourceStripe")},
			"airbyte_source_survey_sparrow":                 {Tok: airbyteDataSource(airbyteMod, "getSourceSurveySparrow")},
			"airbyte_source_surveymonkey":                   {Tok: airbyteDataSource(airbyteMod, "getSourceSurveymonkey")},
			"airbyte_source_tempo":                          {Tok: airbyteDataSource(airbyteMod, "getSourceTempo")},
			"airbyte_source_the_guardian_api":               {Tok: airbyteDataSource(airbyteMod, "getSourceTheGuardianApi")},
			"airbyte_source_tiktok_marketing":               {Tok: airbyteDataSource(airbyteMod, "getSourceTiktokMarketing")},
			"airbyte_source_todoist":                        {Tok: airbyteDataSource(airbyteMod, "getSourceTodoist")},
			"airbyte_source_trello":                         {Tok: airbyteDataSource(airbyteMod, "getSourceTrello")},
			"airbyte_source_trustpilot":                     {Tok: airbyteDataSource(airbyteMod, "getSourceTrustpilot")},
			"airbyte_source_tvmaze_schedule":                {Tok: airbyteDataSource(airbyteMod, "getSourceTvmazeSchedule")},
			"airbyte_source_twilio":                         {Tok: airbyteDataSource(airbyteMod, "getSourceTwilio")},
			"airbyte_source_twilio_taskrouter":              {Tok: airbyteDataSource(airbyteMod, "getSourceTwilioTaskrouter")},
			"airbyte_source_twitter":                        {Tok: airbyteDataSource(airbyteMod, "getSourceTwitter")},
			"airbyte_source_typeform":                       {Tok: airbyteDataSource(airbyteMod, "getSourceTypeform")},
			"airbyte_source_us_census":                      {Tok: airbyteDataSource(airbyteMod, "getSourceUsCensus")},
			"airbyte_source_vantage":                        {Tok: airbyteDataSource(airbyteMod, "getSourceVantage")},
			"airbyte_source_webflow":                        {Tok: airbyteDataSource(airbyteMod, "getSourceWebflow")},
			"airbyte_source_whisky_hunter":                  {Tok: airbyteDataSource(airbyteMod, "getSourceWhiskyHunter")},
			"airbyte_source_wikipedia_pageviews":            {Tok: airbyteDataSource(airbyteMod, "getSourceWikipediaPageviews")},
			"airbyte_source_woocommerce":                    {Tok: airbyteDataSource(airbyteMod, "getSourceWoocommerce")},
			"airbyte_source_xero":                           {Tok: airbyteDataSource(airbyteMod, "getSourceXero")},
			"airbyte_source_xkcd":                           {Tok: airbyteDataSource(airbyteMod, "getSourceXkcd")},
			"airbyte_source_yandex_metrica":                 {Tok: airbyteDataSource(airbyteMod, "getSourceYandexMetrica")},
			"airbyte_source_yotpo":                          {Tok: airbyteDataSource(airbyteMod, "getSourceYotpo")},
			"airbyte_source_younium":                        {Tok: airbyteDataSource(airbyteMod, "getSourceYounium")},
			"airbyte_source_youtube_analytics":              {Tok: airbyteDataSource(airbyteMod, "getSourceYoutubeAnalytics")},
			"airbyte_source_zendesk_chat":                   {Tok: airbyteDataSource(airbyteMod, "getSourceZendeskChat")},
			"airbyte_source_zendesk_sunshine":               {Tok: airbyteDataSource(airbyteMod, "getSourceZendeskSunshine")},
			"airbyte_source_zendesk_support":                {Tok: airbyteDataSource(airbyteMod, "getSourceZendeskSupport")},
			"airbyte_source_zendesk_talk":                   {Tok: airbyteDataSource(airbyteMod, "getSourceZendeskTalk")},
			"airbyte_source_zenloop":                        {Tok: airbyteDataSource(airbyteMod, "getSourceZenloop")},
			"airbyte_source_zoho_crm":                       {Tok: airbyteDataSource(airbyteMod, "getSourceZohoCrm")},
			"airbyte_source_zoom":                           {Tok: airbyteDataSource(airbyteMod, "getSourceZoom")},
			"airbyte_source_zuora":                          {Tok: airbyteDataSource(airbyteMod, "getSourceZuora")},
		},
		JavaScript: &tfbridge.JavaScriptInfo{
			// List any npm dependencies and their versions
			Dependencies: map[string]string{
				"@pulumi/pulumi": "^3.0.0",
			},
			DevDependencies: map[string]string{
				"@types/node": "^10.0.0", // so we can access strongly typed node definitions.
				"@types/mime": "^2.0.0",
			},
		},
		Python: &tfbridge.PythonInfo{
			Requires: map[string]string{
				"pulumi": ">=3.0.0,<4.0.0",
			},
		},
		Golang: &tfbridge.GolangInfo{
			ImportBasePath: filepath.Join(
				fmt.Sprintf("github.com/ryan-pip/pulumi-%[1]s/sdk/", airbytePkg),
				tfbridge.GetModuleMajorVersion(version.Version),
				"go",
				airbytePkg,
			),
			GenerateResourceContainerTypes: true,
		},
		CSharp: &tfbridge.CSharpInfo{
			PackageReferences: map[string]string{
				"Pulumi": "3.*",
			},
			Namespaces: map[string]string{
				"airbyte": "Airbyte",
			},
		},
	}
	return info
}
