// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationGcsConfigurationFormatDestinationGcsUpdateOutputFormatParquetColumnarStorageGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("blockSizeMb")]
        public Input<int>? BlockSizeMb { get; set; }

        [Input("compressionCodec")]
        public Input<string>? CompressionCodec { get; set; }

        [Input("dictionaryEncoding")]
        public Input<bool>? DictionaryEncoding { get; set; }

        [Input("dictionaryPageSizeKb")]
        public Input<int>? DictionaryPageSizeKb { get; set; }

        [Input("formatType", required: true)]
        public Input<string> FormatType { get; set; } = null!;

        [Input("maxPaddingSizeMb")]
        public Input<int>? MaxPaddingSizeMb { get; set; }

        [Input("pageSizeKb")]
        public Input<int>? PageSizeKb { get; set; }

        public DestinationGcsConfigurationFormatDestinationGcsUpdateOutputFormatParquetColumnarStorageGetArgs()
        {
        }
        public static new DestinationGcsConfigurationFormatDestinationGcsUpdateOutputFormatParquetColumnarStorageGetArgs Empty => new DestinationGcsConfigurationFormatDestinationGcsUpdateOutputFormatParquetColumnarStorageGetArgs();
    }
}
