// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationOracleConfigurationTunnelMethodArgs : global::Pulumi.ResourceArgs
    {
        [Input("destinationOracleSshTunnelMethodNoTunnel")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleSshTunnelMethodNoTunnelArgs>? DestinationOracleSshTunnelMethodNoTunnel { get; set; }

        [Input("destinationOracleSshTunnelMethodPasswordAuthentication")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleSshTunnelMethodPasswordAuthenticationArgs>? DestinationOracleSshTunnelMethodPasswordAuthentication { get; set; }

        [Input("destinationOracleSshTunnelMethodSshKeyAuthentication")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleSshTunnelMethodSshKeyAuthenticationArgs>? DestinationOracleSshTunnelMethodSshKeyAuthentication { get; set; }

        [Input("destinationOracleUpdateSshTunnelMethodNoTunnel")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleUpdateSshTunnelMethodNoTunnelArgs>? DestinationOracleUpdateSshTunnelMethodNoTunnel { get; set; }

        [Input("destinationOracleUpdateSshTunnelMethodPasswordAuthentication")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleUpdateSshTunnelMethodPasswordAuthenticationArgs>? DestinationOracleUpdateSshTunnelMethodPasswordAuthentication { get; set; }

        [Input("destinationOracleUpdateSshTunnelMethodSshKeyAuthentication")]
        public Input<Inputs.DestinationOracleConfigurationTunnelMethodDestinationOracleUpdateSshTunnelMethodSshKeyAuthenticationArgs>? DestinationOracleUpdateSshTunnelMethodSshKeyAuthentication { get; set; }

        public DestinationOracleConfigurationTunnelMethodArgs()
        {
        }
        public static new DestinationOracleConfigurationTunnelMethodArgs Empty => new DestinationOracleConfigurationTunnelMethodArgs();
    }
}
