// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationGcsConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("credential", required: true)]
        public Input<Inputs.DestinationGcsConfigurationCredentialGetArgs> Credential { get; set; } = null!;

        [Input("destinationType", required: true)]
        public Input<string> DestinationType { get; set; } = null!;

        [Input("format", required: true)]
        public Input<Inputs.DestinationGcsConfigurationFormatGetArgs> Format { get; set; } = null!;

        [Input("gcsBucketName", required: true)]
        public Input<string> GcsBucketName { get; set; } = null!;

        [Input("gcsBucketPath", required: true)]
        public Input<string> GcsBucketPath { get; set; } = null!;

        [Input("gcsBucketRegion")]
        public Input<string>? GcsBucketRegion { get; set; }

        public DestinationGcsConfigurationGetArgs()
        {
        }
        public static new DestinationGcsConfigurationGetArgs Empty => new DestinationGcsConfigurationGetArgs();
    }
}
