// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationDynamodbConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyId", required: true)]
        public Input<string> AccessKeyId { get; set; } = null!;

        [Input("destinationType", required: true)]
        public Input<string> DestinationType { get; set; } = null!;

        [Input("dynamodbEndpoint")]
        public Input<string>? DynamodbEndpoint { get; set; }

        [Input("dynamodbRegion", required: true)]
        public Input<string> DynamodbRegion { get; set; } = null!;

        [Input("dynamodbTableNamePrefix", required: true)]
        public Input<string> DynamodbTableNamePrefix { get; set; } = null!;

        [Input("secretAccessKey", required: true)]
        public Input<string> SecretAccessKey { get; set; } = null!;

        public DestinationDynamodbConfigurationArgs()
        {
        }
        public static new DestinationDynamodbConfigurationArgs Empty => new DestinationDynamodbConfigurationArgs();
    }
}
