// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationS3GlueConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyId")]
        public Input<string>? AccessKeyId { get; set; }

        [Input("destinationType", required: true)]
        public Input<string> DestinationType { get; set; } = null!;

        [Input("fileNamePattern")]
        public Input<string>? FileNamePattern { get; set; }

        [Input("format", required: true)]
        public Input<Inputs.DestinationS3GlueConfigurationFormatArgs> Format { get; set; } = null!;

        [Input("glueDatabase", required: true)]
        public Input<string> GlueDatabase { get; set; } = null!;

        [Input("glueSerializationLibrary", required: true)]
        public Input<string> GlueSerializationLibrary { get; set; } = null!;

        [Input("s3BucketName", required: true)]
        public Input<string> S3BucketName { get; set; } = null!;

        [Input("s3BucketPath", required: true)]
        public Input<string> S3BucketPath { get; set; } = null!;

        [Input("s3BucketRegion", required: true)]
        public Input<string> S3BucketRegion { get; set; } = null!;

        [Input("s3Endpoint")]
        public Input<string>? S3Endpoint { get; set; }

        [Input("s3PathFormat")]
        public Input<string>? S3PathFormat { get; set; }

        [Input("secretAccessKey")]
        public Input<string>? SecretAccessKey { get; set; }

        public DestinationS3GlueConfigurationArgs()
        {
        }
        public static new DestinationS3GlueConfigurationArgs Empty => new DestinationS3GlueConfigurationArgs();
    }
}
