// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceRecurlyConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey", required: true)]
        public Input<string> ApiKey { get; set; } = null!;

        [Input("beginTime")]
        public Input<string>? BeginTime { get; set; }

        [Input("endTime")]
        public Input<string>? EndTime { get; set; }

        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        public SourceRecurlyConfigurationArgs()
        {
        }
        public static new SourceRecurlyConfigurationArgs Empty => new SourceRecurlyConfigurationArgs();
    }
}
