// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderHttpsPublicWebGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("storage", required: true)]
        public Input<string> Storage { get; set; } = null!;

        [Input("userAgent")]
        public Input<bool>? UserAgent { get; set; }

        public SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderHttpsPublicWebGetArgs()
        {
        }
        public static new SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderHttpsPublicWebGetArgs Empty => new SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderHttpsPublicWebGetArgs();
    }
}
