// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceAmazonAdsConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("authType")]
        public Input<string>? AuthType { get; set; }

        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        [Input("clientSecret", required: true)]
        public Input<string> ClientSecret { get; set; } = null!;

        [Input("lookBackWindow")]
        public Input<int>? LookBackWindow { get; set; }

        [Input("profiles")]
        private InputList<int>? _profiles;
        public InputList<int> Profiles
        {
            get => _profiles ?? (_profiles = new InputList<int>());
            set => _profiles = value;
        }

        [Input("refreshToken", required: true)]
        public Input<string> RefreshToken { get; set; } = null!;

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("reportRecordTypes")]
        private InputList<string>? _reportRecordTypes;
        public InputList<string> ReportRecordTypes
        {
            get => _reportRecordTypes ?? (_reportRecordTypes = new InputList<string>());
            set => _reportRecordTypes = value;
        }

        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        [Input("startDate")]
        public Input<string>? StartDate { get; set; }

        [Input("stateFilters")]
        private InputList<string>? _stateFilters;
        public InputList<string> StateFilters
        {
            get => _stateFilters ?? (_stateFilters = new InputList<string>());
            set => _stateFilters = value;
        }

        public SourceAmazonAdsConfigurationArgs()
        {
        }
        public static new SourceAmazonAdsConfigurationArgs Empty => new SourceAmazonAdsConfigurationArgs();
    }
}
