// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderS3AmazonWebServicesArgs : global::Pulumi.ResourceArgs
    {
        [Input("awsAccessKeyId")]
        public Input<string>? AwsAccessKeyId { get; set; }

        [Input("awsSecretAccessKey")]
        public Input<string>? AwsSecretAccessKey { get; set; }

        [Input("storage", required: true)]
        public Input<string> Storage { get; set; } = null!;

        public SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderS3AmazonWebServicesArgs()
        {
        }
        public static new SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderS3AmazonWebServicesArgs Empty => new SourceFileSecureConfigurationProviderSourceFileSecureUpdateStorageProviderS3AmazonWebServicesArgs();
    }
}
