// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceE2eTestCloudConfigurationMockCatalogSourceE2eTestCloudMockCatalogMultiSchemaArgs : global::Pulumi.ResourceArgs
    {
        [Input("streamSchemas", required: true)]
        public Input<string> StreamSchemas { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public SourceE2eTestCloudConfigurationMockCatalogSourceE2eTestCloudMockCatalogMultiSchemaArgs()
        {
        }
        public static new SourceE2eTestCloudConfigurationMockCatalogSourceE2eTestCloudMockCatalogMultiSchemaArgs Empty => new SourceE2eTestCloudConfigurationMockCatalogSourceE2eTestCloudMockCatalogMultiSchemaArgs();
    }
}
