// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleDirectoryConfigurationCredentialsSourceGoogleDirectoryGoogleCredentialsServiceAccountKeyArgs : global::Pulumi.ResourceArgs
    {
        [Input("credentialsJson", required: true)]
        public Input<string> CredentialsJson { get; set; } = null!;

        [Input("credentialsTitle")]
        public Input<string>? CredentialsTitle { get; set; }

        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        public SourceGoogleDirectoryConfigurationCredentialsSourceGoogleDirectoryGoogleCredentialsServiceAccountKeyArgs()
        {
        }
        public static new SourceGoogleDirectoryConfigurationCredentialsSourceGoogleDirectoryGoogleCredentialsServiceAccountKeyArgs Empty => new SourceGoogleDirectoryConfigurationCredentialsSourceGoogleDirectoryGoogleCredentialsServiceAccountKeyArgs();
    }
}
