// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOrbConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey", required: true)]
        public Input<string> ApiKey { get; set; } = null!;

        [Input("lookbackWindowDays")]
        public Input<int>? LookbackWindowDays { get; set; }

        [Input("numericEventPropertiesKeys")]
        private InputList<string>? _numericEventPropertiesKeys;
        public InputList<string> NumericEventPropertiesKeys
        {
            get => _numericEventPropertiesKeys ?? (_numericEventPropertiesKeys = new InputList<string>());
            set => _numericEventPropertiesKeys = value;
        }

        [Input("planId")]
        public Input<string>? PlanId { get; set; }

        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        [Input("stringEventPropertiesKeys")]
        private InputList<string>? _stringEventPropertiesKeys;
        public InputList<string> StringEventPropertiesKeys
        {
            get => _stringEventPropertiesKeys ?? (_stringEventPropertiesKeys = new InputList<string>());
            set => _stringEventPropertiesKeys = value;
        }

        [Input("subscriptionUsageGroupingKey")]
        public Input<string>? SubscriptionUsageGroupingKey { get; set; }

        public SourceOrbConfigurationArgs()
        {
        }
        public static new SourceOrbConfigurationArgs Empty => new SourceOrbConfigurationArgs();
    }
}
