// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceMicrosoftTeamsConfigurationCredentialsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("sourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoft")]
        public Input<Inputs.SourceMicrosoftTeamsConfigurationCredentialsSourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoftGetArgs>? SourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoft { get; set; }

        [Input("sourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoftOAuth20")]
        public Input<Inputs.SourceMicrosoftTeamsConfigurationCredentialsSourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoftOAuth20GetArgs>? SourceMicrosoftTeamsAuthenticationMechanismAuthenticateViaMicrosoftOAuth20 { get; set; }

        [Input("sourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoft")]
        public Input<Inputs.SourceMicrosoftTeamsConfigurationCredentialsSourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoftGetArgs>? SourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoft { get; set; }

        [Input("sourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoftOAuth20")]
        public Input<Inputs.SourceMicrosoftTeamsConfigurationCredentialsSourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoftOAuth20GetArgs>? SourceMicrosoftTeamsUpdateAuthenticationMechanismAuthenticateViaMicrosoftOAuth20 { get; set; }

        public SourceMicrosoftTeamsConfigurationCredentialsGetArgs()
        {
        }
        public static new SourceMicrosoftTeamsConfigurationCredentialsGetArgs Empty => new SourceMicrosoftTeamsConfigurationCredentialsGetArgs();
    }
}
