// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOracleConfigurationConnectionDataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("sourceOracleConnectByServiceName")]
        public Input<Inputs.SourceOracleConfigurationConnectionDataSourceOracleConnectByServiceNameGetArgs>? SourceOracleConnectByServiceName { get; set; }

        [Input("sourceOracleConnectBySystemIdSid")]
        public Input<Inputs.SourceOracleConfigurationConnectionDataSourceOracleConnectBySystemIdSidGetArgs>? SourceOracleConnectBySystemIdSid { get; set; }

        [Input("sourceOracleUpdateConnectByServiceName")]
        public Input<Inputs.SourceOracleConfigurationConnectionDataSourceOracleUpdateConnectByServiceNameGetArgs>? SourceOracleUpdateConnectByServiceName { get; set; }

        [Input("sourceOracleUpdateConnectBySystemIdSid")]
        public Input<Inputs.SourceOracleConfigurationConnectionDataSourceOracleUpdateConnectBySystemIdSidGetArgs>? SourceOracleUpdateConnectBySystemIdSid { get; set; }

        public SourceOracleConfigurationConnectionDataGetArgs()
        {
        }
        public static new SourceOracleConfigurationConnectionDataGetArgs Empty => new SourceOracleConfigurationConnectionDataGetArgs();
    }
}
