// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGithubConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("branch")]
        public Input<string>? Branch { get; set; }

        [Input("credentials")]
        public Input<Inputs.SourceGithubConfigurationCredentialsGetArgs>? Credentials { get; set; }

        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        [Input("requestsPerHour")]
        public Input<int>? RequestsPerHour { get; set; }

        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        public SourceGithubConfigurationGetArgs()
        {
        }
        public static new SourceGithubConfigurationGetArgs Empty => new SourceGithubConfigurationGetArgs();
    }
}
