// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGitlabConfigurationCredentialsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("sourceGitlabAuthorizationMethodOAuth20")]
        public Input<Inputs.SourceGitlabConfigurationCredentialsSourceGitlabAuthorizationMethodOAuth20GetArgs>? SourceGitlabAuthorizationMethodOAuth20 { get; set; }

        [Input("sourceGitlabAuthorizationMethodPrivateToken")]
        public Input<Inputs.SourceGitlabConfigurationCredentialsSourceGitlabAuthorizationMethodPrivateTokenGetArgs>? SourceGitlabAuthorizationMethodPrivateToken { get; set; }

        [Input("sourceGitlabUpdateAuthorizationMethodOAuth20")]
        public Input<Inputs.SourceGitlabConfigurationCredentialsSourceGitlabUpdateAuthorizationMethodOAuth20GetArgs>? SourceGitlabUpdateAuthorizationMethodOAuth20 { get; set; }

        [Input("sourceGitlabUpdateAuthorizationMethodPrivateToken")]
        public Input<Inputs.SourceGitlabConfigurationCredentialsSourceGitlabUpdateAuthorizationMethodPrivateTokenGetArgs>? SourceGitlabUpdateAuthorizationMethodPrivateToken { get; set; }

        public SourceGitlabConfigurationCredentialsGetArgs()
        {
        }
        public static new SourceGitlabConfigurationCredentialsGetArgs Empty => new SourceGitlabConfigurationCredentialsGetArgs();
    }
}
