// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOracleConfigurationEncryptionSourceOracleEncryptionTlsEncryptedVerifyCertificateArgs : global::Pulumi.ResourceArgs
    {
        [Input("encryptionMethod", required: true)]
        public Input<string> EncryptionMethod { get; set; } = null!;

        [Input("sslCertificate", required: true)]
        public Input<string> SslCertificate { get; set; } = null!;

        public SourceOracleConfigurationEncryptionSourceOracleEncryptionTlsEncryptedVerifyCertificateArgs()
        {
        }
        public static new SourceOracleConfigurationEncryptionSourceOracleEncryptionTlsEncryptedVerifyCertificateArgs Empty => new SourceOracleConfigurationEncryptionSourceOracleEncryptionTlsEncryptedVerifyCertificateArgs();
    }
}
