// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDestinationBigquery(args: GetDestinationBigqueryArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationBigqueryResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationBigquery:getDestinationBigquery", {
        "destinationId": args.destinationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDestinationBigquery.
 */
export interface GetDestinationBigqueryArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationBigquery.
 */
export interface GetDestinationBigqueryResult {
    readonly configuration: outputs.GetDestinationBigqueryConfiguration;
    readonly destinationId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
export function getDestinationBigqueryOutput(args: GetDestinationBigqueryOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDestinationBigqueryResult> {
    return pulumi.output(args).apply((a: any) => getDestinationBigquery(a, opts))
}

/**
 * A collection of arguments for invoking getDestinationBigquery.
 */
export interface GetDestinationBigqueryOutputArgs {
    destinationId: pulumi.Input<string>;
}
