// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * SourceFacebookPages DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFacebookpages = airbyte.getSourceFacebookPages({
 *     secretId: "...my_secret_id...",
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFacebookPages(args: GetSourceFacebookPagesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFacebookPagesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFacebookPages:getSourceFacebookPages", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceFacebookPages.
 */
export interface GetSourceFacebookPagesArgs {
    /**
     * Optional secretID obtained through the public API OAuth redirect flow.
     */
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFacebookPages.
 */
export interface GetSourceFacebookPagesResult {
    readonly configuration: outputs.GetSourceFacebookPagesConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    /**
     * Optional secretID obtained through the public API OAuth redirect flow.
     */
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
/**
 * SourceFacebookPages DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFacebookpages = airbyte.getSourceFacebookPages({
 *     secretId: "...my_secret_id...",
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFacebookPagesOutput(args: GetSourceFacebookPagesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceFacebookPagesResult> {
    return pulumi.output(args).apply((a: any) => getSourceFacebookPages(a, opts))
}

/**
 * A collection of arguments for invoking getSourceFacebookPages.
 */
export interface GetSourceFacebookPagesOutputArgs {
    /**
     * Optional secretID obtained through the public API OAuth redirect flow.
     */
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
