// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFreshsales(args: GetSourceFreshsalesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFreshsalesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFreshsales:getSourceFreshsales", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceFreshsales.
 */
export interface GetSourceFreshsalesArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFreshsales.
 */
export interface GetSourceFreshsalesResult {
    readonly configuration: outputs.GetSourceFreshsalesConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceFreshsalesOutput(args: GetSourceFreshsalesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceFreshsalesResult> {
    return pulumi.output(args).apply((a: any) => getSourceFreshsales(a, opts))
}

/**
 * A collection of arguments for invoking getSourceFreshsales.
 */
export interface GetSourceFreshsalesOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
