// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceExchangeRates(args: GetSourceExchangeRatesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceExchangeRatesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceExchangeRates:getSourceExchangeRates", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesResult {
    readonly configuration: outputs.GetSourceExchangeRatesConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceExchangeRatesOutput(args: GetSourceExchangeRatesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceExchangeRatesResult> {
    return pulumi.output(args).apply((a: any) => getSourceExchangeRates(a, opts))
}

/**
 * A collection of arguments for invoking getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
