// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceIp2whois(args: GetSourceIp2whoisArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceIp2whoisResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceIp2whois:getSourceIp2whois", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceIp2whois.
 */
export interface GetSourceIp2whoisArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceIp2whois.
 */
export interface GetSourceIp2whoisResult {
    readonly configuration: outputs.GetSourceIp2whoisConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceIp2whoisOutput(args: GetSourceIp2whoisOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceIp2whoisResult> {
    return pulumi.output(args).apply((a: any) => getSourceIp2whois(a, opts))
}

/**
 * A collection of arguments for invoking getSourceIp2whois.
 */
export interface GetSourceIp2whoisOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
