// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMarketo(args: GetSourceMarketoArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMarketoResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMarketo:getSourceMarketo", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceMarketo.
 */
export interface GetSourceMarketoArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMarketo.
 */
export interface GetSourceMarketoResult {
    readonly configuration: outputs.GetSourceMarketoConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceMarketoOutput(args: GetSourceMarketoOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceMarketoResult> {
    return pulumi.output(args).apply((a: any) => getSourceMarketo(a, opts))
}

/**
 * A collection of arguments for invoking getSourceMarketo.
 */
export interface GetSourceMarketoOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
