// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceWoocommerce(args: GetSourceWoocommerceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWoocommerceResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWoocommerce:getSourceWoocommerce", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceWoocommerce.
 */
export interface GetSourceWoocommerceArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWoocommerce.
 */
export interface GetSourceWoocommerceResult {
    readonly configuration: outputs.GetSourceWoocommerceConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceWoocommerceOutput(args: GetSourceWoocommerceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceWoocommerceResult> {
    return pulumi.output(args).apply((a: any) => getSourceWoocommerce(a, opts))
}

/**
 * A collection of arguments for invoking getSourceWoocommerce.
 */
export interface GetSourceWoocommerceOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
