// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFreshcaller(args: GetSourceFreshcallerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFreshcallerResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFreshcaller:getSourceFreshcaller", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceFreshcaller.
 */
export interface GetSourceFreshcallerArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFreshcaller.
 */
export interface GetSourceFreshcallerResult {
    readonly configuration: outputs.GetSourceFreshcallerConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceFreshcallerOutput(args: GetSourceFreshcallerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceFreshcallerResult> {
    return pulumi.output(args).apply((a: any) => getSourceFreshcaller(a, opts))
}

/**
 * A collection of arguments for invoking getSourceFreshcaller.
 */
export interface GetSourceFreshcallerOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
