// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTwilio(args: GetSourceTwilioArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTwilioResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTwilio:getSourceTwilio", {
        "secretId": args.secretId,
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceTwilio.
 */
export interface GetSourceTwilioArgs {
    secretId?: string;
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTwilio.
 */
export interface GetSourceTwilioResult {
    readonly configuration: outputs.GetSourceTwilioConfiguration;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly secretId?: string;
    readonly sourceId: string;
    readonly workspaceId: string;
}
export function getSourceTwilioOutput(args: GetSourceTwilioOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceTwilioResult> {
    return pulumi.output(args).apply((a: any) => getSourceTwilio(a, opts))
}

/**
 * A collection of arguments for invoking getSourceTwilio.
 */
export interface GetSourceTwilioOutputArgs {
    secretId?: pulumi.Input<string>;
    sourceId: pulumi.Input<string>;
}
